// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class BindErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.BindError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitBindError(w);
        w.WriteLine();
        EmitBindErrorAsyncFunc(w);
        w.WriteLine();
        EmitBindErrorAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindError<T>(Operation<T>, Func<Error, Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitBindError(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> BindError<T>(this Operation<T> op, Func<Error, Operation<T>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure f => binder(f.Error),");
        w.WriteLine("Operation<T>.Success s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindErrorAsync<T>(Operation<T>, Func<Error, Task<Operation<T>>>)
    // ---------------------------------------------------------------------
    private static void EmitBindErrorAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> BindErrorAsync<T>(this Operation<T> op, Func<Error, Task<Operation<T>>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure f => await binder(f.Error).ConfigureAwait(false),");
        w.WriteLine("Operation<T>.Success s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindErrorAsync<T>(Operation<T>, Task<Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitBindErrorAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> BindErrorAsync<T>(this Operation<T> op, Task<Operation<T>> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure => await task.ConfigureAwait(false),");
        w.WriteLine("Operation<T>.Success s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}