// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class BindEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Bind.g.cs";

    public string Emit(OperationModel op)
    {
        var w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitBind(w);
        w.WriteLine();
        EmitBindAsyncFunc(w);
        w.WriteLine();
        EmitBindAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Bind<T, U>(Operation<T>, Func<T, Operation<U>>)
    // ---------------------------------------------------------------------
    private static void EmitBind(CodeWriter w)
    {
        w.WriteLine("public static Operation<U> Bind<T, U>(this Operation<T> op, Func<T, Operation<U>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => binder(s.Result),");
        w.WriteLine("Operation<T>.Failure f => FailureOf<U>(f.Error),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindAsync<T, U>(Operation<T>, Func<T, Task<Operation<U>>>)
    // ---------------------------------------------------------------------
    private static void EmitBindAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<U>> BindAsync<T, U>(this Operation<T> op, Func<T, Task<Operation<U>>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => await binder(s.Result).ConfigureAwait(false),");
        w.WriteLine("Operation<T>.Failure f => FailureOf<U>(f.Error),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindAsync<T, U>(Operation<T>, Task<Operation<U>>)
    // ---------------------------------------------------------------------
    private static void EmitBindAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<U>> BindAsync<T, U>(this Operation<T> op, Task<Operation<U>> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success => await task.ConfigureAwait(false),");
        w.WriteLine("Operation<T>.Failure f => FailureOf<U>(f.Error),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}