// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationBindEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}BindExtensions");
        sb.AppendLine("{");

        EmitBind(sb, model, fqOp);
        EmitBindAsync(sb, model, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBind(StringBuilder sb, UnionModel model, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<U> Bind<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, " + fqOp + "<U>> binder)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → binder(T)
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => binder(s.Result),");

        // Failure(Error, T?) → Failure(Error, default)
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => new {fqOp}<U>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitBindAsync(StringBuilder sb, UnionModel model, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<U>> BindAsync<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, Task<" + fqOp + "<U>>> binder)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → await binder(T)
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => await binder(s.Result),");

        // Failure(Error, T?) → Failure(Error, default)
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => new {fqOp}<U>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}