// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class EnsureEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Ensure.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitEnsureMessage(w);
        w.WriteLine();
        EmitEnsureError(w);
        w.WriteLine();
        EmitEnsureAsyncMessage(w);
        w.WriteLine();
        EmitEnsureAsyncError(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Ensure<T>(Func<T, bool>, string)
    // ---------------------------------------------------------------------
    private static void EmitEnsureMessage(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Ensure<T>(this Operation<T> op, Func<T, bool> predicate, string message)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => predicate(s.Result) ? op : FailureOf<T>(new Error.Validation(message)),");
        w.WriteLine("Operation<T>.Failure f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Ensure<T>(Func<T, bool>, Error)
    // ---------------------------------------------------------------------
    private static void EmitEnsureError(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Ensure<T>(this Operation<T> op, Func<T, bool> predicate, Error error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => predicate(s.Result) ? op : FailureOf<T>(error),");
        w.WriteLine("Operation<T>.Failure f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // EnsureAsync<T>(Func<T, Task<bool>>, string)
    // ---------------------------------------------------------------------
    private static void EmitEnsureAsyncMessage(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> EnsureAsync<T>(this Operation<T> op, Func<T, Task<bool>> predicate, string message)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => await predicate(s.Result).ConfigureAwait(false) ? op : FailureOf<T>(new Error.Validation(message)),");
        w.WriteLine("Operation<T>.Failure f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // EnsureAsync<T>(Func<T, Task<bool>>, Error)
    // ---------------------------------------------------------------------
    private static void EmitEnsureAsyncError(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> EnsureAsync<T>(this Operation<T> op, Func<T, Task<bool>> predicate, Error error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => await predicate(s.Result).ConfigureAwait(false) ? op : FailureOf<T>(error),");
        w.WriteLine("Operation<T>.Failure f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}