// Copyright (c) 2026 Paulo Pocinho.

using System.Linq;
using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class ErrorToStringEmitter
{
    public static string Emit(UnionModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();

        // Open the outer Error record
        sb.AppendLine($"partial record {model.Name}");
        sb.AppendLine("{");

        foreach (var c in model.Cases)
        {
            EmitCaseToString(sb, c);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitCaseToString(
        StringBuilder sb,
        UnionCaseModel c)
    {
        sb.AppendLine($"    partial record {c.Name}");
        sb.AppendLine("    {");
        sb.AppendLine("        public override string ToString()");
        sb.AppendLine("        {");

        var fields = string.Join(", ",
            c.Fields.Select(f =>
                $"{f.Name}={{FormatValue(this.{f.Name})}}"));

        sb.AppendLine($"            return $\"{c.Name}({fields})\";");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string FormatValue(object? value)");
        sb.AppendLine("            => value switch");
        sb.AppendLine("            {");
        sb.AppendLine("                null => \"null\",");
        sb.AppendLine("                string s => $\"\\\"{s}\\\"\",");
        sb.AppendLine("                Exception ex => ex.ToString(),");
        sb.AppendLine("                _ => value.ToString() ?? \"null\"");
        sb.AppendLine("            };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}