// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class ErrorMatchEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqError = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("public static class ErrorExtensions");
        sb.AppendLine("{");

        EmitMatch(sb, model, fqError);
        EmitMatchAsync(sb, model, fqError);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMatch(StringBuilder sb, UnionModel model, string fqError)
    {
        sb.AppendLine("    public static T Match<T>(");
        sb.AppendLine($"        this {fqError} error,");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string fqCase = $"{fqError}.{c.Name}{FormatGenericArgs(c)}";
            sb.AppendLine($"        Func<{fqCase}, T> {ToParamName(c.Name)},");
        }

        sb.AppendLine($"        Func<{fqError}, T> fallback)");
        sb.AppendLine("        => error switch");
        sb.AppendLine("        {");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string fqCase = $"{fqError}.{c.Name}{FormatGenericArgs(c)}";
            string param = ToParamName(c.Name);
            sb.AppendLine($"            {fqCase} x => {param}(x),");
        }

        sb.AppendLine("            _ => fallback(error)");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitMatchAsync(StringBuilder sb, UnionModel model, string fqError)
    {
        sb.AppendLine("    public static Task<T> MatchAsync<T>(");
        sb.AppendLine($"        this {fqError} error,");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string fqCase = $"{fqError}.{c.Name}{FormatGenericArgs(c)}";
            sb.AppendLine($"        Func<{fqCase}, Task<T>> {ToParamName(c.Name)},");
        }

        sb.AppendLine($"        Func<{fqError}, Task<T>> fallback)");
        sb.AppendLine("        => error switch");
        sb.AppendLine("        {");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string fqCase = $"{fqError}.{c.Name}{FormatGenericArgs(c)}";
            string param = ToParamName(c.Name);
            sb.AppendLine($"            {fqCase} x => {param}(x),");
        }

        sb.AppendLine("            _ => fallback(error)");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static string FormatGenericArgs(UnionCaseModel c)
        => c.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", c.GenericParameters) + ">";

    private static string ToParamName(string caseName)
    {
        if (string.IsNullOrEmpty(caseName) || caseName.Length == 1)
            return caseName.ToLowerInvariant();

        return char.ToLowerInvariant(caseName[0]) + caseName.Substring(1);
    }
}