// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class FailEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Fail.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFailError(w);
        w.WriteLine();
        EmitFailMessage(w);
        w.WriteLine();
        EmitFailValidation(w);
        w.WriteLine();
        EmitFailException(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // Fail<T>(Error error)
    private static void EmitFailError(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Fail<T>(Error error)");
        w.WriteLine("    => FailureOf<T>(error);");
    }

    // Fail<T>(string message)
    private static void EmitFailMessage(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Fail<T>(string message)");
        w.WriteLine("    => FailureOf<T>(new Error.Unexpected(message));");
    }

    // Fail<T>(string message, params string[] fields)
    private static void EmitFailValidation(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Fail<T>(string message, params string[] fields)");
        w.WriteLine("    => FailureOf<T>(new Error.Validation(message, fields));");
    }

    // Fail<T>(Exception ex)
    private static void EmitFailException(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Fail<T>(Exception ex)");
        w.WriteLine("    => FailureOf<T>(new Error.Unexpected(ex.Message, ex));");
    }
}