// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class FinallyEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Finally.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFinally(w);
        w.WriteLine();
        EmitFinallyAsync(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Finally<T>(Action)
    // ---------------------------------------------------------------------
    private static void EmitFinally(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Finally<T>(this Operation<T> op, Action action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("action();");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FinallyAsync<T>(Func<Task>)
    // ---------------------------------------------------------------------
    private static void EmitFinallyAsync(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> FinallyAsync<T>(this Operation<T> op, Func<Task> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("await action().ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }
}