// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class FlattenEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Flatten.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFlatten(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Flatten<T>(Operation<Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitFlatten(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Flatten<T>(this Operation<Operation<T>> op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Success(innerOp)
        w.WriteLine("case Operation<Operation<T>>.Success s:");
        w.Indent();
        w.WriteLine("return s.Result;"); // inner Operation<T>
        w.Unindent();
        w.WriteLine();

        // Failure(error)
        w.WriteLine("case Operation<Operation<T>>.Failure f:");
        w.Indent();
        w.WriteLine("return Operation.FailureOf<T>(f.Error);");
        w.Unindent();
        w.WriteLine();

        // Unknown state
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}