// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class FromEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.From.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSuccess(w);
        w.WriteLine();
        EmitFailureOf(w);
        w.WriteLine();
        EmitFromValue(w);
        w.WriteLine();
        EmitFromError(w);
        w.WriteLine();
        EmitFromFunc(w);
        w.WriteLine();
        EmitFromFuncAsync(w);
        w.WriteLine();
        EmitFromTaskAsync(w);
        w.WriteLine();
        EmitFromException(w);
        w.WriteLine();
        EmitFromNullable(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Success<T>
    // ---------------------------------------------------------------------
    private static void EmitSuccess(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Success<T>(T value)");
        w.WriteLine("    => new Operation<T>.Success(value);");
    }

    // ---------------------------------------------------------------------
    // FailureOf<T>  (renamed to avoid conflict with nested record type)
    // ---------------------------------------------------------------------
    private static void EmitFailureOf(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> FailureOf<T>(Error error)");
        w.WriteLine("    => new Operation<T>.Failure(error);");
    }

    // ---------------------------------------------------------------------
    // FromValue<T>
    // ---------------------------------------------------------------------
    private static void EmitFromValue(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> FromValue<T>(T value)");
        w.WriteLine("    => Success(value);");
    }

    // ---------------------------------------------------------------------
    // FromError<T>
    // ---------------------------------------------------------------------
    private static void EmitFromError(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> FromError<T>(Error error)");
        w.WriteLine("    => FailureOf<T>(error);");
    }

    // ---------------------------------------------------------------------
    // From(Func<T>)
    // ---------------------------------------------------------------------
    private static void EmitFromFunc(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> From<T>(Func<T> func)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(func());");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return FailureOf<T>(new Error.Unexpected(ex.Message, ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromAsync(Func<Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitFromFuncAsync(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> FromAsync<T>(Func<Task<T>> func)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(await func().ConfigureAwait(false));");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return FailureOf<T>(new Error.Unexpected(ex.Message, ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromAsync(Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitFromTaskAsync(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> FromAsync<T>(Task<T> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(await task.ConfigureAwait(false));");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return FailureOf<T>(new Error.Unexpected(ex.Message, ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromException<T>
    // ---------------------------------------------------------------------
    private static void EmitFromException(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> FromException<T>(Exception ex)");
        w.WriteLine("    => FailureOf<T>(new Error.Unexpected(ex.Message, ex));");
    }

    // ---------------------------------------------------------------------
    // FromNullable<T>
    // ---------------------------------------------------------------------
    private static void EmitFromNullable(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> FromNullable<T>(T? value, string? message = null)");
        w.WriteLine("    where T : class");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return value is not null");
        w.Indent();
        w.WriteLine("? Success(value)");
        w.WriteLine(": FailureOf<T>(new Error.Unexpected(message ?? $\"Value of type {typeof(T).Name} was null.\"));");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
    }
}