// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class MapEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Map.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMap(w);
        w.WriteLine();
        EmitMapAsyncFunc(w);
        w.WriteLine();
        EmitMapAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Map<T, U>(Operation<T>, Func<T, U>)
    // ---------------------------------------------------------------------
    private static void EmitMap(CodeWriter w)
    {
        w.WriteLine("public static Operation<U> Map<T, U>(this Operation<T> op, Func<T, U> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => Success(mapper(s.Result)),");
        w.WriteLine("Operation<T>.Failure f => FailureOf<U>(f.Error),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapAsync<T, U>(Operation<T>, Func<T, Task<U>>)
    // ---------------------------------------------------------------------
    private static void EmitMapAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<U>> MapAsync<T, U>(this Operation<T> op, Func<T, Task<U>> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success s => Success(await mapper(s.Result).ConfigureAwait(false)),");
        w.WriteLine("Operation<T>.Failure f => FailureOf<U>(f.Error),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapAsync<T, U>(Operation<T>, Task<U>)
    // ---------------------------------------------------------------------
    private static void EmitMapAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<U>> MapAsync<T, U>(this Operation<T> op, Task<U> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Success => Success(await task.ConfigureAwait(false)),");
        w.WriteLine("Operation<T>.Failure f => FailureOf<U>(f.Error),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}