// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class MapErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.MapError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMapError(w);
        w.WriteLine();
        EmitMapErrorAsyncFunc(w);
        w.WriteLine();
        EmitMapErrorAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapError<T>(Operation<T>, Func<Error, Error>)
    // ---------------------------------------------------------------------
    private static void EmitMapError(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> MapError<T>(this Operation<T> op, Func<Error, Error> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure f => FailureOf<T>(mapper(f.Error)),");
        w.WriteLine("Operation<T>.Success s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapErrorAsync<T>(Operation<T>, Func<Error, Task<Error>>)
    // ---------------------------------------------------------------------
    private static void EmitMapErrorAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> MapErrorAsync<T>(this Operation<T> op, Func<Error, Task<Error>> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure f => FailureOf<T>(await mapper(f.Error).ConfigureAwait(false)),");
        w.WriteLine("Operation<T>.Success s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapErrorAsync<T>(Operation<T>, Task<Error>)
    // ---------------------------------------------------------------------
    private static void EmitMapErrorAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> MapErrorAsync<T>(this Operation<T> op, Task<Error> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure => FailureOf<T>(await task.ConfigureAwait(false)),");
        w.WriteLine("Operation<T>.Success s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}