// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationMapEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}MapExtensions");
        sb.AppendLine("{");

        EmitMap(sb, model, fqOp);
        EmitMapAsync(sb, model, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMap(StringBuilder sb, UnionModel model, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<U> Map<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, U> mapper)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            {fqOp}<T>.Success s => " +
            $"new {fqOp}<U>.Success(mapper(s.Result)),");

        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => " +
            $"new {fqOp}<U>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitMapAsync(StringBuilder sb, UnionModel model, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<U>> MapAsync<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, Task<U>> mapper)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            {fqOp}<T>.Success s => " +
            $"new {fqOp}<U>.Success(await mapper(s.Result)),");

        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => " +
            $"new {fqOp}<U>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}