// Copyright (c) 2026 Paulo Pocinho.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class MatchEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}MatchExtensions");
        sb.AppendLine("{");

        EmitMatch(sb, model);
        EmitMatchAsync(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMatch(StringBuilder sb, UnionModel model)
    {
        string methodGenerics = BuildMethodGenericParams(model, "TResult");

        sb.AppendLine($"    public static TResult Match{methodGenerics}(");
        sb.AppendLine($"        this {model.FullyQualifiedName}{FormatGenericArgs(model)} value,");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string handlerSig = BuildHandlerSignature(c, model);
            sb.AppendLine($"        {handlerSig} {ToParamName(c.Name)},");
        }

        sb.Length -= 3;
        sb.AppendLine(")");
        sb.AppendLine("        => value switch");
        sb.AppendLine("        {");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string fqCase = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}.{c.Name}{FormatGenericArgs(c)}";
            string args = BuildHandlerArguments(c, model);
            sb.AppendLine($"            {fqCase} x => {ToParamName(c.Name)}({args}),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown union case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitMatchAsync(StringBuilder sb, UnionModel model)
    {
        string methodGenerics = BuildMethodGenericParams(model, "TResult");

        sb.AppendLine($"    public static Task<TResult> MatchAsync{methodGenerics}(");
        sb.AppendLine($"        this {model.FullyQualifiedName}{FormatGenericArgs(model)} value,");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string handlerSig = BuildAsyncHandlerSignature(c, model);
            sb.AppendLine($"        {handlerSig} {ToParamName(c.Name)},");
        }

        sb.Length -= 3;
        sb.AppendLine(")");
        sb.AppendLine("        => value switch");
        sb.AppendLine("        {");

        foreach (UnionCaseModel? c in model.Cases)
        {
            string fqCase = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}.{c.Name}{FormatGenericArgs(c)}";
            string args = BuildHandlerArguments(c, model);
            sb.AppendLine($"            {fqCase} x => {ToParamName(c.Name)}({args}),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown union case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static string BuildHandlerSignature(UnionCaseModel c, UnionModel model)
    {
        List<CaseField> allFields = model.BaseFields.Concat(c.Fields).ToList();

        if (allFields.Count == 0)
            return "Func<TResult>";

        string types = string.Join(", ", allFields.Select(f => f.Type));
        return $"Func<{types}, TResult>";
    }

    private static string BuildAsyncHandlerSignature(UnionCaseModel c, UnionModel model)
    {
        List<CaseField> allFields = model.BaseFields.Concat(c.Fields).ToList();

        if (allFields.Count == 0)
            return "Func<Task<TResult>>";

        string types = string.Join(", ", allFields.Select(f => f.Type));
        return $"Func<{types}, Task<TResult>>";
    }

    private static string BuildHandlerArguments(UnionCaseModel c, UnionModel model)
    {
        List<CaseField> allFields = model.BaseFields.Concat(c.Fields).ToList();

        if (allFields.Count == 0)
            return "";

        return string.Join(", ", allFields.Select(f => $"x.{f.Name}"));
    }

    private static string FormatGenericArgs(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";

    private static string FormatGenericArgs(UnionCaseModel c)
        => c.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", c.GenericParameters) + ">";

    private static string BuildMethodGenericParams(UnionModel model, string resultName)
    {
        // For non-generic unions: <TResult>
        // For Operation<T>: <T, TResult>
        List<string> all = model.GenericParameters.Concat(new[] { resultName }).ToList();
        return "<" + string.Join(", ", all) + ">";
    }

    private static string ToParamName(string name)
        => char.ToLowerInvariant(name[0]) + name.Substring(1);
}