// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class MatchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Match.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMatch(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Match<T, TResult>(Func<T, TResult>, Func<Error, TResult>)
    // ---------------------------------------------------------------------
    private static void EmitMatch(CodeWriter w)
    {
        w.WriteLine("public static TResult Match<T, TResult>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, TResult> onSuccess,");
        w.WriteLine("Func<Error, TResult> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("case Operation<T>.Success s:");
        w.Indent();
        w.WriteLine("return onSuccess(s.Result);");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("case Operation<T>.Failure f:");
        w.Indent();
        w.WriteLine("return onFailure(f.Error);");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}