// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationFinallyEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}FinallyExtensions");
        sb.AppendLine("{");

        EmitFinally(sb, model);
        EmitFinallyAsync(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------
    // FINALLY (sync)
    // -------------------------------------------------------
    private static void EmitFinally(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static {type} Finally{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine("        Action action)");
        sb.AppendLine("    {");
        sb.AppendLine("        action();");
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // FINALLY ASYNC
    // -------------------------------------------------------
    private static void EmitFinallyAsync(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static async Task<{type}> FinallyAsync{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine("        Func<Task> action)");
        sb.AppendLine("    {");
        sb.AppendLine("        await action().ConfigureAwait(false);");
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // Helpers
    // -------------------------------------------------------
    private static string FormatGenericArgs(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";

    private static string FormatMethodGenerics(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";
}