// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationWhereEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}WhereExtensions");
        sb.AppendLine("{");

        EmitWhere(sb, fqOp);
        EmitWhereAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitWhere(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<T> Where<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, bool> predicate)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            {fqOp}<T>.Success s => " +
            $"predicate(s.Result) ? op : new {fqOp}<T>.Failure(new Error.Validation(\"Predicate failed\"), default),");

        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => f,");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitWhereAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<T>> WhereAsync<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, Task<bool>> predicate)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            {fqOp}<T>.Success s => " +
            $"await predicate(s.Result) ? op : new {fqOp}<T>.Failure(new Error.Validation(\"Predicate failed\"), default),");

        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => f,");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}