// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationIfEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}IfExtensions");
        sb.AppendLine("{");

        EmitIfSuccess(sb, model);
        EmitIfSuccessAsync(sb, model);
        EmitIfFailure(sb, model);
        EmitIfFailureAsync(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------
    // IfSuccess (sync)
    // -------------------------------------------------------
    private static void EmitIfSuccess(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";
        string t = model.GenericParameters[0];

        sb.AppendLine($"    public static {type} IfSuccess{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine($"        Action<{t}> action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Success s)");
        sb.AppendLine("            action(s.Result);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // IfSuccessAsync
    // -------------------------------------------------------
    private static void EmitIfSuccessAsync(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";
        string t = model.GenericParameters[0];

        sb.AppendLine($"    public static async Task<{type}> IfSuccessAsync{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine($"        Func<{t}, Task> action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Success s)");
        sb.AppendLine("            await action(s.Result).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // IfFailure (sync)
    // -------------------------------------------------------
    private static void EmitIfFailure(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static {type} IfFailure{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine("        Action<Error> action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Failure f)");
        sb.AppendLine("            action(f.Error);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // IfFailureAsync
    // -------------------------------------------------------
    private static void EmitIfFailureAsync(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static async Task<{type}> IfFailureAsync{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine("        Func<Error, Task> action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Failure f)");
        sb.AppendLine("            await action(f.Error).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // Helpers
    // -------------------------------------------------------
    private static string FormatGenericArgs(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";

    private static string FormatMethodGenerics(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";
}