// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationFallbackEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}FallbackExtensions");
        sb.AppendLine("{");

        EmitFallback(sb, fqOp);
        EmitFallbackAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFallback(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<T> Fallback<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<Error, {fqOp}<T>> fallback)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → keep success
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → fallback(error)
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => fallback(f.Error),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitFallbackAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<T>> FallbackAsync<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<Error, Task<{fqOp}<T>>> fallback)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → keep success
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → await fallback(error)
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => await fallback(f.Error),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}