// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationToStringEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();

        // Open the outer Operation<T> record
        sb.AppendLine($"partial record {model.Name}<T>");
        sb.AppendLine("{");

        EmitSuccessToString(sb);
        EmitFailureToString(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitSuccessToString(StringBuilder sb)
    {
        sb.AppendLine("    partial record Success");
        sb.AppendLine("    {");
        sb.AppendLine("        public override string ToString()");
        sb.AppendLine("        {");
        sb.AppendLine("            return $\"Success(Result={FormatValue(this.Result)})\";");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string FormatValue(object? value)");
        sb.AppendLine("            => value switch");
        sb.AppendLine("            {");
        sb.AppendLine("                null => \"null\",");
        sb.AppendLine("                string s => $\"\\\"{s}\\\"\",");
        sb.AppendLine("                _ => value.ToString() ?? \"null\"");
        sb.AppendLine("            };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitFailureToString(StringBuilder sb)
    {
        sb.AppendLine("    partial record Failure");
        sb.AppendLine("    {");
        sb.AppendLine("        public override string ToString()");
        sb.AppendLine("        {");
        sb.AppendLine("            return $\"Failure(Error={this.Error}, Result={FormatValue(this.Result)})\";");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static string FormatValue(object? value)");
        sb.AppendLine("            => value switch");
        sb.AppendLine("            {");
        sb.AppendLine("                null => \"null\",");
        sb.AppendLine("                string s => $\"\\\"{s}\\\"\",");
        sb.AppendLine("                _ => value.ToString() ?? \"null\"");
        sb.AppendLine("            };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}