// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationEnsureEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}EnsureExtensions");
        sb.AppendLine("{");

        EmitEnsure(sb, model);
        EmitEnsureAsync(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------
    // Ensure (sync)
    // -------------------------------------------------------
    private static void EmitEnsure(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";
        string t = model.GenericParameters[0];

        sb.AppendLine($"    public static {type} Ensure{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine($"        Func<{t}, bool> predicate,");
        sb.AppendLine("        Func<Error> errorFactory)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Success s)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!predicate(s.Result))");
        sb.AppendLine("                return new " + type + ".Failure(errorFactory(), default);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // EnsureAsync
    // -------------------------------------------------------
    private static void EmitEnsureAsync(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";
        string t = model.GenericParameters[0];

        sb.AppendLine($"    public static async Task<{type}> EnsureAsync{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine($"        Func<{t}, Task<bool>> predicateAsync,");
        sb.AppendLine("        Func<Error> errorFactory)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Success s)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!await predicateAsync(s.Result).ConfigureAwait(false))");
        sb.AppendLine("                return new " + type + ".Failure(errorFactory(), default);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // Helpers
    // -------------------------------------------------------
    private static string FormatGenericArgs(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";

    private static string FormatMethodGenerics(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";
}