// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationOrElseEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}OrElseExtensions");
        sb.AppendLine("{");

        EmitOrElse(sb, fqOp);
        EmitOrElseAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitOrElse(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<T> OrElse<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<{fqOp}<T>> alternative)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → keep success
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → alternative()
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => alternative(),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitOrElseAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<T>> OrElseAsync<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<Task<{fqOp}<T>>> alternative)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → keep success
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → await alternative()
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => await alternative(),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}