// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationRecoverEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}RecoverExtensions");
        sb.AppendLine("{");

        EmitRecover(sb, fqOp);
        EmitRecoverAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRecover(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<T> Recover<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<Error, T> recover)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → keep success
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → Success(recover(error))
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => new {fqOp}<T>.Success(recover(f.Error)),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitRecoverAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<T>> RecoverAsync<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<Error, Task<T>> recover)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → keep success
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → Success(await recover(error))
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => new {fqOp}<T>.Success(await recover(f.Error)),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}