// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationLinqEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}LinqExtensions");
        sb.AppendLine("{");

        EmitSelect(sb, fqOp);
        EmitSelectAsync(sb, fqOp);
        EmitSelectMany(sb, fqOp);
        EmitSelectManyAsync(sb, fqOp);
        EmitSelectManyWithProjection(sb, fqOp);
        EmitSelectManyWithProjectionAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---------------------------
    // SELECT (Map)
    // ---------------------------
    private static void EmitSelect(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<U> Select<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, U> selector)");
        sb.AppendLine("        => op.Map(selector);");
        sb.AppendLine();
    }

    private static void EmitSelectAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static Task<{fqOp}<U>> SelectAsync<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<T, Task<U>> selector)");
        sb.AppendLine("        => op.MapAsync(selector);");
        sb.AppendLine();
    }

    // ---------------------------
    // SELECT MANY (Bind)
    // ---------------------------
    private static void EmitSelectMany(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<U> SelectMany<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<T, {fqOp}<U>> binder)");
        sb.AppendLine("        => op.Bind(binder);");
        sb.AppendLine();
    }

    private static void EmitSelectManyAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static Task<{fqOp}<U>> SelectManyAsync<T, U>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<T, Task<{fqOp}<U>>> binder)");
        sb.AppendLine("        => op.BindAsync(binder);");
        sb.AppendLine();
    }

    // ---------------------------
    // SELECT MANY with projection (LINQ query syntax)
    // ---------------------------
    private static void EmitSelectManyWithProjection(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<R> SelectMany<T, U, R>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<T, {fqOp}<U>> binder,");
        sb.AppendLine("        Func<T, U, R> projector)");
        sb.AppendLine("        => op.Bind(t =>");
        sb.AppendLine("            binder(t).Map(u => projector(t, u)));");
        sb.AppendLine();
    }

    private static void EmitSelectManyWithProjectionAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static Task<{fqOp}<R>> SelectManyAsync<T, U, R>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine($"        Func<T, Task<{fqOp}<U>>> binder,");
        sb.AppendLine("        Func<T, U, R> projector)");
        sb.AppendLine("        => op.BindAsync(async t =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var inner = await binder(t);");
        sb.AppendLine("            return inner.Map(u => projector(t, u));");
        sb.AppendLine("        });");
        sb.AppendLine();
    }
}