// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationMapErrorEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}MapErrorExtensions");
        sb.AppendLine("{");

        EmitMapError(sb, fqOp);
        EmitMapErrorAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMapError(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<T> MapError<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<Error, Error> mapper)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → unchanged
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → Failure(mappedError, default)
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => new {fqOp}<T>.Failure(mapper(f.Error), default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitMapErrorAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<T>> MapErrorAsync<T>(");
        sb.AppendLine($"        this {fqOp}<T> op,");
        sb.AppendLine("        Func<Error, Task<Error>> mapper)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(T) → unchanged
        sb.AppendLine(
            $"            {fqOp}<T>.Success s => s,");

        // Failure(Error, T?) → Failure(await mappedError, default)
        sb.AppendLine(
            $"            {fqOp}<T>.Failure f => new {fqOp}<T>.Failure(await mapper(f.Error), default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }
}