// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationCombineEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}CombineExtensions");
        sb.AppendLine("{");

        EmitCombine2(sb, fqOp);
        EmitCombine3(sb, fqOp);
        EmitCombine4(sb, fqOp);

        EmitCombineAsync2(sb, fqOp);
        EmitCombineAsync3(sb, fqOp);
        EmitCombineAsync4(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------
    // Combine 2
    // -------------------------------------------------------
    private static void EmitCombine2(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<(T1, T2)> Combine<T1, T2>(");
        sb.AppendLine($"        {fqOp}<T1> op1,");
        sb.AppendLine($"        {fqOp}<T2> op2)");
        sb.AppendLine("        => (op1, op2) switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            ({fqOp}<T1>.Success s1, {fqOp}<T2>.Success s2) => " +
            $"new {fqOp}<(T1, T2)>.Success((s1.Result, s2.Result)),");

        sb.AppendLine(
            $"            ({fqOp}<T1>.Failure f, _) => " +
            $"new {fqOp}<(T1, T2)>.Failure(f.Error, default),");

        sb.AppendLine(
            $"            (_, {fqOp}<T2>.Failure f) => " +
            $"new {fqOp}<(T1, T2)>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // Combine 3
    // -------------------------------------------------------
    private static void EmitCombine3(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<(T1, T2, T3)> Combine<T1, T2, T3>(");
        sb.AppendLine($"        {fqOp}<T1> op1,");
        sb.AppendLine($"        {fqOp}<T2> op2,");
        sb.AppendLine($"        {fqOp}<T3> op3)");
        sb.AppendLine("        => (op1, op2, op3) switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            ({fqOp}<T1>.Success s1, {fqOp}<T2>.Success s2, {fqOp}<T3>.Success s3) => " +
            $"new {fqOp}<(T1, T2, T3)>.Success((s1.Result, s2.Result, s3.Result)),");

        sb.AppendLine(
            $"            ({fqOp}<T1>.Failure f, _, _) => " +
            $"new {fqOp}<(T1, T2, T3)>.Failure(f.Error, default),");

        sb.AppendLine(
            $"            (_, {fqOp}<T2>.Failure f, _) => " +
            $"new {fqOp}<(T1, T2, T3)>.Failure(f.Error, default),");

        sb.AppendLine(
            $"            (_, _, {fqOp}<T3>.Failure f) => " +
            $"new {fqOp}<(T1, T2, T3)>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // Combine 4
    // -------------------------------------------------------
    private static void EmitCombine4(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<(T1, T2, T3, T4)> Combine<T1, T2, T3, T4>(");
        sb.AppendLine($"        {fqOp}<T1> op1,");
        sb.AppendLine($"        {fqOp}<T2> op2,");
        sb.AppendLine($"        {fqOp}<T3> op3,");
        sb.AppendLine($"        {fqOp}<T4> op4)");
        sb.AppendLine("        => (op1, op2, op3, op4) switch");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            ({fqOp}<T1>.Success s1, {fqOp}<T2>.Success s2, {fqOp}<T3>.Success s3, {fqOp}<T4>.Success s4) => " +
            $"new {fqOp}<(T1, T2, T3, T4)>.Success((s1.Result, s2.Result, s3.Result, s4.Result)),");

        sb.AppendLine(
            $"            ({fqOp}<T1>.Failure f, _, _, _) => " +
            $"new {fqOp}<(T1, T2, T3, T4)>.Failure(f.Error, default),");

        sb.AppendLine(
            $"            (_, {fqOp}<T2>.Failure f, _, _) => " +
            $"new {fqOp}<(T1, T2, T3, T4)>.Failure(f.Error, default),");

        sb.AppendLine(
            $"            (_, _, {fqOp}<T3>.Failure f, _) => " +
            $"new {fqOp}<(T1, T2, T3, T4)>.Failure(f.Error, default),");

        sb.AppendLine(
            $"            (_, _, _, {fqOp}<T4>.Failure f) => " +
            $"new {fqOp}<(T1, T2, T3, T4)>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // CombineAsync 2
    // -------------------------------------------------------
    private static void EmitCombineAsync2(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<(T1, T2)>> CombineAsync<T1, T2>(");
        sb.AppendLine($"        Task<{fqOp}<T1>> op1Task,");
        sb.AppendLine($"        Task<{fqOp}<T2>> op2Task)");
        sb.AppendLine("    {");
        sb.AppendLine("        var op1 = await op1Task;");
        sb.AppendLine("        var op2 = await op2Task;");
        sb.AppendLine("        return Combine(op1, op2);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // CombineAsync 3
    // -------------------------------------------------------
    private static void EmitCombineAsync3(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<(T1, T2, T3)>> CombineAsync<T1, T2, T3>(");
        sb.AppendLine($"        Task<{fqOp}<T1>> op1Task,");
        sb.AppendLine($"        Task<{fqOp}<T2>> op2Task,");
        sb.AppendLine($"        Task<{fqOp}<T3>> op3Task)");
        sb.AppendLine("    {");
        sb.AppendLine("        var op1 = await op1Task;");
        sb.AppendLine("        var op2 = await op2Task;");
        sb.AppendLine("        var op3 = await op3Task;");
        sb.AppendLine("        return Combine(op1, op2, op3);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -------------------------------------------------------
    // CombineAsync 4
    // -------------------------------------------------------
    private static void EmitCombineAsync4(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<(T1, T2, T3, T4)>> CombineAsync<T1, T2, T3, T4>(");
        sb.AppendLine($"        Task<{fqOp}<T1>> op1Task,");
        sb.AppendLine($"        Task<{fqOp}<T2>> op2Task,");
        sb.AppendLine($"        Task<{fqOp}<T3>> op3Task,");
        sb.AppendLine($"        Task<{fqOp}<T4>> op4Task)");
        sb.AppendLine("    {");
        sb.AppendLine("        var op1 = await op1Task;");
        sb.AppendLine("        var op2 = await op2Task;");
        sb.AppendLine("        var op3 = await op3Task;");
        sb.AppendLine("        var op4 = await op4Task;");
        sb.AppendLine("        return Combine(op1, op2, op3, op4);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}