// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class OperationFlattenEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        string fqOp = model.FullyQualifiedName;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}FlattenExtensions");
        sb.AppendLine("{");

        EmitFlatten(sb, fqOp);
        EmitFlattenAsync(sb, fqOp);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFlatten(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static {fqOp}<T> Flatten<T>(");
        sb.AppendLine($"        this {fqOp}<{fqOp}<T>> op)");
        sb.AppendLine("        => op switch");
        sb.AppendLine("        {");

        // Success(Operation<T>) → inner
        sb.AppendLine(
            $"            {fqOp}<{fqOp}<T>>.Success s => s.Result ?? " +
            $"new {fqOp}<T>.Failure(new Error.Unexpected(\"Flattened null\"), default),");

        // Failure(Error, Operation<T>?) → Failure(Error)
        sb.AppendLine(
            $"            {fqOp}<{fqOp}<T>>.Failure f => " +
            $"new {fqOp}<T>.Failure(f.Error, default),");

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Unknown Operation case\")");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitFlattenAsync(StringBuilder sb, string fqOp)
    {
        sb.AppendLine($"    public static async Task<{fqOp}<T>> FlattenAsync<T>(");
        sb.AppendLine($"        this Task<{fqOp}<{fqOp}<T>>> opTask)");
        sb.AppendLine("    {");
        sb.AppendLine("        var op = await opTask;");
        sb.AppendLine("        return op.Flatten();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}