// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class RecoverEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Recover.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitRecover(w);
        w.WriteLine();
        EmitRecoverAsyncFunc(w);
        w.WriteLine();
        EmitRecoverAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Recover<T>(Func<Error, T>)
    // ---------------------------------------------------------------------
    private static void EmitRecover(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Recover<T>(this Operation<T> op, Func<Error, T> recover)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure f => Success(recover(f.Error)),");
        w.WriteLine("Operation<T>.Success s => s,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Func<Error, Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> RecoverAsync<T>(this Operation<T> op, Func<Error, Task<T>> recover)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure f => Success(await recover(f.Error).ConfigureAwait(false)),");
        w.WriteLine("Operation<T>.Success s => s,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> RecoverAsync<T>(this Operation<T> op, Task<T> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<T>.Failure => Success(await task.ConfigureAwait(false)),");
        w.WriteLine("Operation<T>.Success s => s,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}