// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class SwitchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Switch.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSwitch(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Switch<T>(Action<T>, Action<Error>)
    // ---------------------------------------------------------------------
    private static void EmitSwitch(CodeWriter w)
    {
        w.WriteLine("public static void Switch<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Action<T> onSuccess,");
        w.WriteLine("Action<Error> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("case Operation<T>.Success s:");
        w.Indent();
        w.WriteLine("onSuccess(s.Result);");
        w.WriteLine("return;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("case Operation<T>.Failure f:");
        w.Indent();
        w.WriteLine("onFailure(f.Error);");
        w.WriteLine("return;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}