// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class TapEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Tap.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitTap(w);
        w.WriteLine();
        EmitTapAsyncFunc(w);
        w.WriteLine();
        EmitTapAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Tap<T>(Action<T>)
    // ---------------------------------------------------------------------
    private static void EmitTap(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> Tap<T>(this Operation<T> op, Action<T> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("case Operation<T>.Success s:");
        w.Indent();
        w.WriteLine("action(s.Result);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();
        w.WriteLine("case Operation<T>.Failure:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapAsync<T>(Func<T, Task>)
    // ---------------------------------------------------------------------
    private static void EmitTapAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> TapAsync<T>(this Operation<T> op, Func<T, Task> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("case Operation<T>.Success s:");
        w.Indent();
        w.WriteLine("await action(s.Result).ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();
        w.WriteLine("case Operation<T>.Failure:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapAsync<T>(Task)
    // ---------------------------------------------------------------------
    private static void EmitTapAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> TapAsync<T>(this Operation<T> op, Func<Task> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("case Operation<T>.Success:");
        w.Indent();
        w.WriteLine("await task().ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();
        w.WriteLine("case Operation<T>.Failure:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

}