// Copyright (c) 2026 Paulo Pocinho.

using System.Text;
using PP.Toolkit.Operation.Generators.Models;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal static class TapEmitter
{
    public static string Emit(UnionModel model)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.Name}TapExtensions");
        sb.AppendLine("{");

        EmitTap(sb, model);
        EmitTapAsync(sb, model);
        EmitTapError(sb, model);
        EmitTapErrorAsync(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -----------------------------
    // SUCCESS-ONLY TAP
    // -----------------------------
    private static void EmitTap(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static {type} Tap{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine($"        Action<{model.GenericParameters[0]}>? onSuccess)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Success s && onSuccess is not null)");
        sb.AppendLine("            onSuccess(s.Result);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -----------------------------
    // SUCCESS-ONLY TAP ASYNC
    // -----------------------------
    private static void EmitTapAsync(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static async Task<{type}> TapAsync{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine($"        Func<{model.GenericParameters[0]}, Task>? onSuccess)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Success s && onSuccess is not null)");
        sb.AppendLine("            await onSuccess(s.Result).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -----------------------------
    // FAILURE-ONLY TAP
    // -----------------------------
    private static void EmitTapError(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static {type} TapError{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine("        Action<Error>? onError)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Failure f && onError is not null)");
        sb.AppendLine("            onError(f.Error);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -----------------------------
    // FAILURE-ONLY TAP ASYNC
    // -----------------------------
    private static void EmitTapErrorAsync(StringBuilder sb, UnionModel model)
    {
        string type = $"{model.FullyQualifiedName}{FormatGenericArgs(model)}";

        sb.AppendLine($"    public static async Task<{type}> TapErrorAsync{FormatMethodGenerics(model)}(");
        sb.AppendLine($"        this {type} op,");
        sb.AppendLine("        Func<Error, Task>? onError)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (op is {type}.Failure f && onError is not null)");
        sb.AppendLine("            await onError(f.Error).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("        return op;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // -----------------------------
    // Helpers
    // -----------------------------
    private static string FormatGenericArgs(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";

    private static string FormatMethodGenerics(UnionModel model)
        => model.GenericParameters.Count == 0
            ? ""
            : "<" + string.Join(", ", model.GenericParameters) + ">";
}