// Copyright (c) 2026 Paulo Pocinho.

using PP.Toolkit.Operation.Generators.Semantics;

namespace PP.Toolkit.Operation.Generators.Emission.Emitters;

internal sealed class TapErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.TapError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w);
    }

    private static void EmitClass(CodeWriter w)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitTapError(w);
        w.WriteLine();
        EmitTapErrorAsyncFunc(w);
        w.WriteLine();
        EmitTapErrorAsyncTask(w);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapError<T>(Action<Error>)
    // ---------------------------------------------------------------------
    private static void EmitTapError(CodeWriter w)
    {
        w.WriteLine("public static Operation<T> TapError<T>(this Operation<T> op, Action<Error> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("case Operation<T>.Failure f:");
        w.Indent();
        w.WriteLine("action(f.Error);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("case Operation<T>.Success:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapErrorAsync<T>(Func<Error, Task>)
    // ---------------------------------------------------------------------
    private static void EmitTapErrorAsyncFunc(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> TapErrorAsync<T>(this Operation<T> op, Func<Error, Task> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("case Operation<T>.Failure f:");
        w.Indent();
        w.WriteLine("await action(f.Error).ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("case Operation<T>.Success:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapErrorAsync<T>(Func<Task>)
    // ---------------------------------------------------------------------
    private static void EmitTapErrorAsyncTask(CodeWriter w)
    {
        w.WriteLine("public static async Task<Operation<T>> TapErrorAsync<T>(this Operation<T> op, Func<Task> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("case Operation<T>.Failure:");
        w.Indent();
        w.WriteLine("await task().ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("case Operation<T>.Success:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }
}