// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class BindErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.BindError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitBindError(w, op);
        w.WriteLine();
        EmitBindErrorAsyncFunc(w, op);
        w.WriteLine();
        EmitBindErrorAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindError<T>(Operation<T>, Func<ErrorType, Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitBindError(CodeWriter w, OperationModel op)
    {
        string failure = op.FailureCaseFQN;
        string success = op.SuccessCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type; // fully qualified

        w.WriteLine($"public static Operation<T> BindError<T>(this Operation<T> op, Func<{errorType}, Operation<T>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => binder(f.{errorField}),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindErrorAsync<T>(Operation<T>, Func<ErrorType, Task<Operation<T>>>)
    // ---------------------------------------------------------------------
    private static void EmitBindErrorAsyncFunc(CodeWriter w, OperationModel op)
    {
        string failure = op.FailureCaseFQN;
        string success = op.SuccessCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine($"public static async Task<Operation<T>> BindErrorAsync<T>(this Operation<T> op, Func<{errorType}, Task<Operation<T>>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => await binder(f.{errorField}).ConfigureAwait(false),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindErrorAsync<T>(Operation<T>, Task<Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitBindErrorAsyncTask(CodeWriter w, OperationModel op)
    {
        string failure = op.FailureCaseFQN;
        string success = op.SuccessCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("public static async Task<Operation<T>> BindErrorAsync<T>(this Operation<T> op, Task<Operation<T>> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} => await task.ConfigureAwait(false),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}