// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class BindEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Bind.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitBind(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    private static void EmitBind(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("public static Operation<U> Bind<T, U>(this Operation<T> op, Func<T, Operation<U>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => binder(s.{resultField}),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}