// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class BindEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Bind.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitBind(w, op);
        w.WriteLine();
        EmitBindAsyncFunc(w, op);
        w.WriteLine();
        EmitBindAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Bind<T, U>(Operation<T>, Func<T, Operation<U>>)
    // ---------------------------------------------------------------------
    private static void EmitBind(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("public static Operation<U> Bind<T, U>(this Operation<T> op, Func<T, Operation<U>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => binder(s.{resultField}),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindAsync<T, U>(Operation<T>, Func<T, Task<Operation<U>>>)
    // ---------------------------------------------------------------------
    private static void EmitBindAsyncFunc(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("public static async Task<Operation<U>> BindAsync<T, U>(this Operation<T> op, Func<T, Task<Operation<U>>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => await binder(s.{resultField}).ConfigureAwait(false),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindAsync<T, U>(Operation<T>, Task<Operation<U>>)
    // ---------------------------------------------------------------------
    private static void EmitBindAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name;

        w.WriteLine("public static async Task<Operation<U>> BindAsync<T, U>(this Operation<T> op, Task<Operation<U>> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} => await task.ConfigureAwait(false),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}