// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class BindErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.BindError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitBindError(w, op);
        w.WriteLine();
        EmitBindErrorAsyncFunc(w, op);
        w.WriteLine();
        EmitBindErrorAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindError<T>(Operation<T>, Func<Error, Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitBindError(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name; // "Result"
        string errorField = op.ErrorField.Name;   // "Error"
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Applies a binder to the error of a failed operation, leaving successes unchanged.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"binder\">The function to apply when the operation is a failure.</param>");
        w.WriteLine("/// <returns>A new operation based on the binder result, or the original success.</returns>");
        w.WriteLine($"public static Operation<T> BindError<T>(this Operation<T> op, Func<{errorType}, Operation<T>> binder)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (binder is null) throw new ArgumentNullException(nameof(binder));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => binder(f.{errorField}),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindErrorAsync<T>(Operation<T>, Func<Error, Task<Operation<T>>>)
    // ---------------------------------------------------------------------
    private static void EmitBindErrorAsyncFunc(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously applies a binder to the error of a failed operation.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"binderAsync\">The async function to apply when the operation is a failure.</param>");
        w.WriteLine("/// <returns>A task producing the bound operation, or the original success.</returns>");
        w.WriteLine($"public static async Task<Operation<T>> BindErrorAsync<T>(this Operation<T> op, Func<{errorType}, Task<Operation<T>>> binderAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (binderAsync is null) throw new ArgumentNullException(nameof(binderAsync));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => await binderAsync(f.{errorField}).ConfigureAwait(false),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // BindErrorAsync<T>(Operation<T>, Task<Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitBindErrorAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously replaces a failed operation with a precomputed operation task.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"nextTask\">The task to use when the operation is a failure.</param>");
        w.WriteLine("/// <returns>A task producing the bound operation, or the original success.</returns>");
        w.WriteLine("public static async Task<Operation<T>> BindErrorAsync<T>(this Operation<T> op, Task<Operation<T>> nextTask)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (nextTask is null) throw new ArgumentNullException(nameof(nextTask));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} => await nextTask.ConfigureAwait(false),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}