// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class EnsureEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Ensure.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitEnsure(w, op);
        w.WriteLine();

        EmitEnsureAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Ensure<T>(Func<T, bool>, Func<T, Error>)
    // ---------------------------------------------------------------------
    private static void EmitEnsure(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Ensures that a successful operation satisfies a predicate; otherwise returns a failure.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<T> Ensure<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, bool> predicate,");
        w.WriteLine("Func<T, Error> errorFactory)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (predicate is null) throw new ArgumentNullException(nameof(predicate));");
        w.WriteLine("if (errorFactory is null) throw new ArgumentNullException(nameof(errorFactory));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Success case
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("if (predicate(s.Result))");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return s;"); // unchanged success
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("return new Operation<T>.Failure(errorFactory(s.Result));");
        w.Unindent();

        // Failure case
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return f;"); // unchanged failure
        w.Unindent();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // EnsureAsync<T>(Func<T, Task<bool>>, Func<T, Error>)
    // ---------------------------------------------------------------------
    private static void EmitEnsureAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously ensures that a successful operation satisfies a predicate; otherwise returns a failure.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> EnsureAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, Task<bool>> predicateAsync,");
        w.WriteLine("Func<T, Error> errorFactory)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (predicateAsync is null) throw new ArgumentNullException(nameof(predicateAsync));");
        w.WriteLine("if (errorFactory is null) throw new ArgumentNullException(nameof(errorFactory));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Success case
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("if (await predicateAsync(s.Result).ConfigureAwait(false))");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return s;"); // unchanged success
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("return new Operation<T>.Failure(errorFactory(s.Result));");
        w.Unindent();

        // Failure case
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return f;"); // unchanged failure
        w.Unindent();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}