// Copyright (c) 2026 Paulo Pocinho.

using System.Linq;
using OpFlow.Generators.Models;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class ErrorToStringEmitter : IErrorEmitter
{
    public string FileName(UnionModel error) => $"{error.Name}.ToString.g.cs";

    public string Emit(UnionModel error)
    {
        CodeWriter w = new CodeWriter();

        // Header
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();

        // Namespace
        w.WriteLine($"namespace {error.Namespace};");
        w.WriteLine();

        // Begin union root
        w.WriteLine($"public abstract partial record {error.Name}");
        w.WriteLine("{");
        w.Indent();

        foreach (UnionCaseModel? c in error.Cases)
        {
            // Emit nested partial record WITHOUT parameter list
            w.WriteLine($"public sealed partial record {c.Name}");
            w.WriteLine("{");
            w.Indent();

            string firstField = c.Fields.First().Name;

            w.WriteLine($"public override string ToString() => \"{c.Name}: \" + {firstField};");

            w.Unindent();
            w.WriteLine("}");
            w.WriteLine();
        }

        w.Unindent();
        w.WriteLine("}");

        return w.ToString();
    }
}