// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FactoryEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Factory.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSuccessFactory(w, op);
        w.WriteLine();
        EmitFailureFactory(w, op);

        w.Unindent();
        w.WriteLine("}");

        return w.ToString();
    }

    private static void EmitSuccessFactory(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string resultType = op.GenericParameter;

        w.WriteLine("/// <summary>Creates a successful operation.</summary>");
        w.WriteLine($"public static Operation<{resultType}> Success<{resultType}>({resultType} value)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return new {success}(value);");
        w.Unindent();
        w.WriteLine("}");
    }

    private static void EmitFailureFactory(CodeWriter w, OperationModel op)
    {
        string failure = op.FailureCaseFQN;
        string resultType = op.GenericParameter;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>Creates a failed operation.</summary>");
        w.WriteLine($"public static Operation<{resultType}> FailureOf<{resultType}>({errorType} error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return new {failure}(error);");
        w.Unindent();
        w.WriteLine("}");
    }
}