// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FactoryEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Factory.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSuccessFactory(w, op);
        w.WriteLine();

        EmitFailureFactory(w, op);
        w.WriteLine();

        EmitFromErrorFactory(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Success<T>(T value)
    // ---------------------------------------------------------------------
    private static void EmitSuccessFactory(CodeWriter w, OperationModel op)
    {
        string resultType = op.GenericParameter;
        string success = op.SuccessCaseFQN;

        w.WriteLine("/// <summary>Creates a successful operation.</summary>");
        w.WriteLine($"public static Operation<{resultType}> Success<{resultType}>({resultType} value)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return new {success}(value);");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FailureOf<T>(Error error)
    // ---------------------------------------------------------------------
    private static void EmitFailureFactory(CodeWriter w, OperationModel op)
    {
        string resultType = op.GenericParameter;
        string errorType = op.ErrorField.Type;
        string failure = op.FailureCaseFQN;

        w.WriteLine("/// <summary>Creates a failed operation.</summary>");
        w.WriteLine($"public static Operation<{resultType}> FailureOf<{resultType}>({errorType} error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return new {failure}(error);");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromError<T>(Error error)
    // ---------------------------------------------------------------------
    private static void EmitFromErrorFactory(CodeWriter w, OperationModel op)
    {
        string resultType = op.GenericParameter;
        string errorType = op.ErrorField.Type;
        string failure = op.FailureCaseFQN;

        w.WriteLine("/// <summary>Creates a failed operation from an existing error.</summary>");
        w.WriteLine($"public static Operation<{resultType}> FromError<{resultType}>({errorType} error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return new {failure}(error);");
        w.Unindent();
        w.WriteLine("}");
    }
}