// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FailEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Fail.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFailError(w, op);
        w.WriteLine();
        EmitFailMessage(w, op);
        w.WriteLine();
        EmitFailValidation(w, op);
        w.WriteLine();
        EmitFailException(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // Fail<T>(ErrorType error)
    private static void EmitFailError(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine($"public static Operation<T> Fail<T>({errorType} error)");
        w.WriteLine("    => FailureOf<T>(error);");
    }

    // Fail<T>(string message)
    private static void EmitFailMessage(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;
        string unexpectedType = $"{errorType}.Unexpected";

        w.WriteLine("public static Operation<T> Fail<T>(string message)");
        w.WriteLine($"    => FailureOf<T>(new {unexpectedType}(message));");
    }

    // Fail<T>(string message, params string[] fields)
    private static void EmitFailValidation(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;
        string validationType = $"{errorType}.Validation";

        w.WriteLine("public static Operation<T> Fail<T>(string message, params string[] fields)");
        w.WriteLine($"    => FailureOf<T>(new {validationType}(message, fields));");
    }

    // Fail<T>(Exception ex)
    private static void EmitFailException(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;
        string unexpectedType = $"{errorType}.Unexpected";

        w.WriteLine("public static Operation<T> Fail<T>(Exception ex)");
        w.WriteLine($"    => FailureOf<T>(new {unexpectedType}(ex.Message, ex));");
    }
}