// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FailEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Fail.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFail(w, op);
        w.WriteLine();
        EmitFailAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Fail<T>(Operation<T>, Func<Error, Error>)
    // ---------------------------------------------------------------------
    private static void EmitFail(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name; // "Error"
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Transforms the error of a failed operation using the provided function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"transform\">The function that transforms the error.</param>");
        w.WriteLine("/// <returns>A new failure with the transformed error, or the original success.</returns>");
        w.WriteLine($"public static Operation<T> Fail<T>(this Operation<T> op, Func<{errorType}, {errorType}> transform)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (transform is null) throw new ArgumentNullException(nameof(transform));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => FailureOf<T>(transform(f.{errorField})),");
        w.WriteLine($"{success} s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FailAsync<T>(Operation<T>, Func<Error, Task<Error>>)
    // ---------------------------------------------------------------------
    private static void EmitFailAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously transforms the error of a failed operation using the provided async function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"transformAsync\">The async function that transforms the error.</param>");
        w.WriteLine("/// <returns>A task producing a new failure with the transformed error, or the original success.</returns>");
        w.WriteLine($"public static async Task<Operation<T>> FailAsync<T>(this Operation<T> op, Func<{errorType}, Task<{errorType}>> transformAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (transformAsync is null) throw new ArgumentNullException(nameof(transformAsync));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => FailureOf<T>(await transformAsync(f.{errorField}).ConfigureAwait(false)),");
        w.WriteLine($"{success} s => Success(s.Result),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}