// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FinallyEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Finally.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFinally(w, op);
        w.WriteLine();
        EmitFinallyAsync(w, op);
        w.WriteLine();
        EmitFinallyAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Finally<T>(Operation<T>, Action<T>, Action<Error>)
    // ---------------------------------------------------------------------
    private static void EmitFinally(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Executes side-effects for both success and failure without altering the result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<T> Finally<T>(");
        w.WriteLine("    this Operation<T> op,");
        w.WriteLine("    Action<T> onSuccess,");
        w.WriteLine("    Action<Error> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"onSuccess(s.{resultField});");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("onFailure(f.Error);");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FinallyAsync<T>(Operation<T>, Action<T>, Action<Error>)
    // ---------------------------------------------------------------------
    private static void EmitFinallyAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes side-effects for both success and failure without altering the result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Task<Operation<T>> FinallyAsync<T>(");
        w.WriteLine("    this Operation<T> op,");
        w.WriteLine("    Action<T> onSuccess,");
        w.WriteLine("    Action<Error> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"    {success} s => Task.FromResult(op.Finally(onSuccess, onFailure)),");
        w.WriteLine($"    {failure} f => Task.FromResult(op.Finally(onSuccess, onFailure)),");
        w.WriteLine("    _ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FinallyAsync<T>(Task<Operation<T>>, Action<T>, Action<Error>)
    // (canonical async shape)
    // ---------------------------------------------------------------------
    private static void EmitFinallyAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes side-effects for both success and failure on an asynchronous operation.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> FinallyAsync<T>(");
        w.WriteLine("    this Task<Operation<T>> opTask,");
        w.WriteLine("    Action<T> onSuccess,");
        w.WriteLine("    Action<Error> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (opTask is null) throw new ArgumentNullException(nameof(opTask));");
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("var op = await opTask.ConfigureAwait(false);");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"onSuccess(s.{resultField});");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("onFailure(f.Error);");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }
}