// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FlattenEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Flatten.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFlatten(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    private static void EmitFlatten(CodeWriter w, OperationModel op)
    {
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("public static Operation<T> Flatten<T>(this Operation<Operation<T>> op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        // Success(innerOp)
        w.WriteLine("global::OpFlow.Operation<Operation<T>>.Success s => s." + resultField + ",");

        // Failure(error)
        w.WriteLine("global::OpFlow.Operation<Operation<T>>.Failure f => FailureOf<T>(f." + errorField + "),");

        // Unknown
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");

        w.Unindent();
        w.WriteLine("}");
    }
}