// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FlattenEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Flatten.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFlatten(w, op);
        w.WriteLine();
        EmitFlattenAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Flatten<T>(Operation<Operation<T>>)
    // ---------------------------------------------------------------------
    private static void EmitFlatten(CodeWriter w, OperationModel op)
    {
        string nestedSuccess = $"global::{op.Namespace}.Operation<Operation<T>>.Success";
        string nestedFailure = $"global::{op.Namespace}.Operation<Operation<T>>.Failure";

        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Flattens a nested operation by removing one level of wrapping.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<T> Flatten<T>(this Operation<Operation<T>> op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{nestedSuccess} s => s.{resultField},");
        w.WriteLine($"{nestedFailure} f => FailureOf<T>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FlattenAsync<T>(Task<Operation<Operation<T>>>)
    // ---------------------------------------------------------------------
    private static void EmitFlattenAsync(CodeWriter w, OperationModel op)
    {
        string nestedSuccess = $"global::{op.Namespace}.Operation<Operation<T>>.Success";
        string nestedFailure = $"global::{op.Namespace}.Operation<Operation<T>>.Failure";

        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously flattens a nested operation by removing one level of wrapping.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> FlattenAsync<T>(this Task<Operation<Operation<T>>> opTask)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("Operation<Operation<T>> op = await opTask.ConfigureAwait(false);");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{nestedSuccess} s => s.{resultField},");
        w.WriteLine($"{nestedFailure} f => FailureOf<T>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}