// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class FromEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.From.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitFromValue(w, op);
        w.WriteLine();
        EmitFromFunc(w, op);
        w.WriteLine();
        EmitFromAsyncFunc(w, op);
        w.WriteLine();
        EmitFromAsyncTask(w, op);
        w.WriteLine();
        EmitFromException(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromValue<T>(T)
    // ---------------------------------------------------------------------
    private static void EmitFromValue(CodeWriter w, OperationModel op)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Wraps a value in a successful operation.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"value\">The value to wrap.</param>");
        w.WriteLine("/// <returns>A successful operation containing the value.</returns>");
        w.WriteLine("public static Operation<T> FromValue<T>(T value)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(value);");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // From<T>(Func<T>)
    // ---------------------------------------------------------------------
    private static void EmitFromFunc(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Executes a function and wraps its result in an operation, capturing exceptions as failures.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"func\">The function to execute.</param>");
        w.WriteLine("/// <returns>A successful operation or a failure if an exception occurs.</returns>");
        w.WriteLine("public static Operation<T> From<T>(Func<T> func)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (func is null) throw new ArgumentNullException(nameof(func));");
        w.WriteLine();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(func());");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromAsync<T>(Func<Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitFromAsyncFunc(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes a function and wraps its result in an operation, capturing exceptions as failures.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"funcAsync\">The async function to execute.</param>");
        w.WriteLine("/// <returns>A task producing a successful operation or a failure if an exception occurs.</returns>");
        w.WriteLine("public static async Task<Operation<T>> FromAsync<T>(Func<Task<T>> funcAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (funcAsync is null) throw new ArgumentNullException(nameof(funcAsync));");
        w.WriteLine();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("T value = await funcAsync().ConfigureAwait(false);");
        w.WriteLine("return Success(value);");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromAsync<T>(Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitFromAsyncTask(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Wraps a task result in an operation, capturing exceptions as failures.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"task\">The task to await.</param>");
        w.WriteLine("/// <returns>A task producing a successful operation or a failure if an exception occurs.</returns>");
        w.WriteLine("public static async Task<Operation<T>> FromAsync<T>(Task<T> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (task is null) throw new ArgumentNullException(nameof(task));");
        w.WriteLine();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("T value = await task.ConfigureAwait(false);");
        w.WriteLine("return Success(value);");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // FromException<T>(Exception)
    // ---------------------------------------------------------------------
    private static void EmitFromException(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Converts an exception into a failed operation.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"ex\">The exception to convert.</param>");
        w.WriteLine("/// <returns>A failed operation containing the converted error.</returns>");
        w.WriteLine("public static Operation<T> FromException<T>(Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (ex is null) throw new ArgumentNullException(nameof(ex));");
        w.WriteLine();
        w.WriteLine("return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
    }
}