// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class IfFailureEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.IfFailure.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitIfFailure(w, op);
        w.WriteLine();
        EmitIfFailureAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // IfFailure<T>(Action<ErrorType>)
    // ---------------------------------------------------------------------
    private static void EmitIfFailure(CodeWriter w, OperationModel op)
    {
        string failure = op.FailureCaseFQN;
        string success = op.SuccessCaseFQN;
        string errorType = op.ErrorField.Type;
        string errorField = op.ErrorField.Name;

        w.WriteLine($"public static Operation<T> IfFailure<T>(this Operation<T> op, Action<{errorType}> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Failure
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"action(f.{errorField});");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Success
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // IfFailureAsync<T>(Func<ErrorType, Task>)
    // ---------------------------------------------------------------------
    private static void EmitIfFailureAsync(CodeWriter w, OperationModel op)
    {
        string failure = op.FailureCaseFQN;
        string success = op.SuccessCaseFQN;
        string errorType = op.ErrorField.Type;
        string errorField = op.ErrorField.Name;

        w.WriteLine($"public static async Task<Operation<T>> IfFailureAsync<T>(this Operation<T> op, Func<{errorType}, Task> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Failure
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"await action(f.{errorField}).ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Success
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }
}