// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class IfSuccessEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.IfSuccess.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitIfSuccess(w, op);
        w.WriteLine();
        EmitIfSuccessAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // IfSuccess<T>(Action<T>)
    // ---------------------------------------------------------------------
    private static void EmitIfSuccess(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("public static Operation<T> IfSuccess<T>(this Operation<T> op, Action<T> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Success
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"action(s.{resultField});");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Failure
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // IfSuccessAsync<T>(Func<T, Task>)
    // ---------------------------------------------------------------------
    private static void EmitIfSuccessAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("public static async Task<Operation<T>> IfSuccessAsync<T>(this Operation<T> op, Func<T, Task> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Success
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"await action(s.{resultField}).ConfigureAwait(false);");
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Failure
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }
}