// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MapErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.MapError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMapError(w, op);
        w.WriteLine();
        EmitMapErrorAsyncFunc(w, op);
        w.WriteLine();
        EmitMapErrorAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapError<T>(Operation<T>, Func<ErrorType, ErrorType>)
    // ---------------------------------------------------------------------
    private static void EmitMapError(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorType = op.ErrorField.Type;
        string errorField = op.ErrorField.Name;
        string resultField = op.ResultField.Name;

        w.WriteLine($"public static Operation<T> MapError<T>(this Operation<T> op, Func<{errorType}, {errorType}> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{failure} f => FailureOf<T>(mapper(f.{errorField})),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapErrorAsync<T>(Operation<T>, Func<ErrorType, Task<ErrorType>>)
    // ---------------------------------------------------------------------
    private static void EmitMapErrorAsyncFunc(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorType = op.ErrorField.Type;
        string errorField = op.ErrorField.Name;
        string resultField = op.ResultField.Name;

        w.WriteLine($"public static async Task<Operation<T>> MapErrorAsync<T>(this Operation<T> op, Func<{errorType}, Task<{errorType}>> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{failure} f => FailureOf<T>(await mapper(f.{errorField}).ConfigureAwait(false)),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapErrorAsync<T>(Operation<T>, Task<ErrorType>)
    // ---------------------------------------------------------------------
    private static void EmitMapErrorAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorType = op.ErrorField.Type;
        string errorField = op.ErrorField.Name;
        string resultField = op.ResultField.Name;

        w.WriteLine($"public static async Task<Operation<T>> MapErrorAsync<T>(this Operation<T> op, Task<{errorType}> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{failure} f => FailureOf<T>(await task.ConfigureAwait(false)),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}