// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MapErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.MapError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMapError(w, op);
        w.WriteLine();
        EmitMapErrorAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapError<T>(Operation<T>, Func<Error, Error>)
    // ---------------------------------------------------------------------
    private static void EmitMapError(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Maps the error of a failed operation using the provided function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<T> MapError<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<Error, Error> mapper)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (mapper is null) throw new ArgumentNullException(nameof(mapper));");
        w.WriteLine();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => s,");
        w.WriteLine($"{failure} f => global::OpFlow.Operation.FailureOf<T>(mapper(f.{errorField})),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapErrorAsync<T>(Operation<T>, Func<Error, Task<Error>>)
    // ---------------------------------------------------------------------
    private static void EmitMapErrorAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously maps the error of a failed operation using the provided async function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> MapErrorAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<Error, Task<Error>> mapperAsync)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (mapperAsync is null) throw new ArgumentNullException(nameof(mapperAsync));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("return s;");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return global::OpFlow.Operation.FailureOf<T>(");
        w.Indent();
        w.WriteLine("await mapperAsync(f.Error).ConfigureAwait(false)");
        w.Unindent();
        w.WriteLine(");");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}