// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MapEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Map.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMap(w, op);
        w.WriteLine();
        EmitMapAsyncFunc(w, op);
        w.WriteLine();
        EmitMapAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Map<T, U>(Operation<T>, Func<T, U>)
    // ---------------------------------------------------------------------
    private static void EmitMap(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name; // "Result"
        string errorField = op.ErrorField.Name;   // "Error"

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Maps the successful result of an operation using the provided function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The input result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"U\">The mapped result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"mapper\">The mapping function.</param>");
        w.WriteLine("/// <returns>A mapped success or the original failure.</returns>");
        w.WriteLine("public static Operation<U> Map<T, U>(this Operation<T> op, Func<T, U> mapper)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (mapper is null) throw new ArgumentNullException(nameof(mapper));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => Success(mapper(s.{resultField})),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapAsync<T, U>(Task<Operation<T>>, Func<T, Task<U>>)
    // ---------------------------------------------------------------------
    private static void EmitMapAsyncFunc(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously maps the successful result of an operation using the provided async function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The input result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"U\">The mapped result type.</typeparam>");
        w.WriteLine("/// <param name=\"opTask\">The source operation task.</param>");
        w.WriteLine("/// <param name=\"mapperAsync\">The async mapping function.</param>");
        w.WriteLine("/// <returns>A task producing a mapped success or the original failure.</returns>");
        w.WriteLine("public static async Task<Operation<U>> MapAsync<T, U>(");
        w.Indent();
        w.WriteLine("this Task<Operation<T>> opTask,");
        w.WriteLine("Func<T, Task<U>> mapperAsync)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (mapperAsync is null) throw new ArgumentNullException(nameof(mapperAsync));");
        w.WriteLine();
        w.WriteLine("Operation<T> op = await opTask.ConfigureAwait(false);");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => Success(await mapperAsync(s.{resultField}).ConfigureAwait(false)),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapAsync<T, U>(Task<Operation<T>>, Task<U>)
    // ---------------------------------------------------------------------
    private static void EmitMapAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously maps the successful result of an operation using a precomputed task.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The input result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"U\">The mapped result type.</typeparam>");
        w.WriteLine("/// <param name=\"opTask\">The source operation task.</param>");
        w.WriteLine("/// <param name=\"nextTask\">The task producing the mapped value.</param>");
        w.WriteLine("/// <returns>A task producing a mapped success or the original failure.</returns>");
        w.WriteLine("public static async Task<Operation<U>> MapAsync<T, U>(");
        w.Indent();
        w.WriteLine("this Task<Operation<T>> opTask,");
        w.WriteLine("Task<U> nextTask)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (nextTask is null) throw new ArgumentNullException(nameof(nextTask));");
        w.WriteLine();
        w.WriteLine("Operation<T> op = await opTask.ConfigureAwait(false);");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} => Success(await nextTask.ConfigureAwait(false)),");
        w.WriteLine($"{failure} f => FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}