// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MapEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Map.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMap(w, op);
        w.WriteLine();
        EmitMapAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Map<T, U>(Operation<T>, Func<T, U>)
    // ---------------------------------------------------------------------
    private static void EmitMap(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Maps the successful result of an operation using the provided function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<U> Map<T, U>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, U> mapper)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (mapper is null) throw new ArgumentNullException(nameof(mapper));");
        w.WriteLine();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => global::OpFlow.Operation.Success(mapper(s.{resultField})),");
        w.WriteLine($"{failure} f => global::OpFlow.Operation.FailureOf<U>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MapAsync<T, U>(Operation<T>, Func<T, Task<U>>)
    // ---------------------------------------------------------------------
    private static void EmitMapAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously maps the successful result of an operation using the provided async function.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<U>> MapAsync<T, U>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, Task<U>> mapperAsync)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (mapperAsync is null) throw new ArgumentNullException(nameof(mapperAsync));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("return global::OpFlow.Operation.Success(");
        w.Indent();
        w.WriteLine("await mapperAsync(s.Result).ConfigureAwait(false)");
        w.Unindent();
        w.WriteLine(");");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return global::OpFlow.Operation.FailureOf<U>(f.Error);");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}