// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MatchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Match.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMatch(w, op);
        w.WriteLine();
        EmitMatchAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Match<T, R>(Operation<T>, Func<T, R>, Func<Error, R>)
    // ---------------------------------------------------------------------
    private static void EmitMatch(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Matches on the operation, executing the appropriate function based on success or failure.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"R\">The return type of the match functions.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"onSuccess\">The function to execute when the operation is a success.</param>");
        w.WriteLine("/// <param name=\"onFailure\">The function to execute when the operation is a failure.</param>");
        w.WriteLine("/// <returns>The result of the executed function.</returns>");
        w.WriteLine($"public static R Match<T, R>(this Operation<T> op, Func<T, R> onSuccess, Func<{errorType}, R> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => onSuccess(s.{resultField}),");
        w.WriteLine($"{failure} f => onFailure(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MatchAsync<T, R>(Operation<T>, Func<T, Task<R>>, Func<Error, Task<R>>)
    // ---------------------------------------------------------------------
    private static void EmitMatchAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously matches on the operation, executing the appropriate function based on success or failure.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"R\">The return type of the match functions.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"onSuccessAsync\">The async function to execute when the operation is a success.</param>");
        w.WriteLine("/// <param name=\"onFailureAsync\">The async function to execute when the operation is a failure.</param>");
        w.WriteLine("/// <returns>A task producing the result of the executed function.</returns>");
        w.WriteLine($"public static async Task<R> MatchAsync<T, R>(this Operation<T> op, Func<T, Task<R>> onSuccessAsync, Func<{errorType}, Task<R>> onFailureAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccessAsync is null) throw new ArgumentNullException(nameof(onSuccessAsync));");
        w.WriteLine("if (onFailureAsync is null) throw new ArgumentNullException(nameof(onFailureAsync));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => await onSuccessAsync(s.{resultField}).ConfigureAwait(false),");
        w.WriteLine($"{failure} f => await onFailureAsync(f.{errorField}).ConfigureAwait(false),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}