// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MatchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Match.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMatch(w, op);
        w.WriteLine();
        EmitMatchAsync(w, op);
        w.WriteLine();
        EmitMatchAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Match<T, R>(Operation<T>, Func<T, R>, Func<Error, R>)
    // ---------------------------------------------------------------------
    private static void EmitMatch(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Matches the operation, invoking the appropriate callback and returning its result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static R Match<T, R>(");
        w.WriteLine("    this Operation<T> op,");
        w.WriteLine("    Func<T, R> onSuccess,");
        w.WriteLine("    Func<Error, R> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"    {success} s => onSuccess(s.{resultField}),");
        w.WriteLine($"    {failure} f => onFailure(f.Error),");
        w.WriteLine("    _ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MatchAsync<T, R>(Operation<T>, Func<T, R>, Func<Error, R>)
    // ---------------------------------------------------------------------
    private static void EmitMatchAsync(CodeWriter w, OperationModel op)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously matches the operation, invoking the appropriate callback and returning its result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Task<R> MatchAsync<T, R>(");
        w.WriteLine("    this Operation<T> op,");
        w.WriteLine("    Func<T, R> onSuccess,");
        w.WriteLine("    Func<Error, R> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("return Task.FromResult(op.Match(onSuccess, onFailure));");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // MatchAsync<T, R>(Task<Operation<T>>, Func<T, R>, Func<Error, R>)
    // (canonical async shape)
    // ---------------------------------------------------------------------
    private static void EmitMatchAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously matches an asynchronous operation, invoking the appropriate callback and returning its result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<R> MatchAsync<T, R>(");
        w.WriteLine("    this Task<Operation<T>> opTask,");
        w.WriteLine("    Func<T, R> onSuccess,");
        w.WriteLine("    Func<Error, R> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (opTask is null) throw new ArgumentNullException(nameof(opTask));");
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("var op = await opTask.ConfigureAwait(false);");
        w.WriteLine();
        w.WriteLine("return op.Match(onSuccess, onFailure);");
        w.Unindent();
        w.WriteLine("}");
    }
}