// <auto-generated />
#nullable enable
using System;
using System.Threading.Tasks;

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class MatchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Match.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitMatchFunctional(w, op);
        w.WriteLine();
        EmitMatchAction(w, op);
        w.WriteLine();
        EmitMatchAsyncAction(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Functional Match<T, TResult>
    // ---------------------------------------------------------------------
    private static void EmitMatchFunctional(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Matches on the operation and returns a value based on success or failure.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static TResult Match<T, TResult>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, TResult> onSuccess,");
        w.WriteLine("Func<Error, TResult> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => onSuccess(s.{resultField}),");
        w.WriteLine($"{failure} f => onFailure(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Side-effect Match<T> (void)
    // ---------------------------------------------------------------------
    private static void EmitMatchAction(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Matches on the operation and executes side-effect actions.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static void Match<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Action<T> onSuccess,");
        w.WriteLine("Action<Error> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("onSuccess(s.Result);");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("onFailure(f.Error);");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Side-effect MatchAsync<T> (Task)
    // ---------------------------------------------------------------------
    private static void EmitMatchAsyncAction(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously matches on the operation and executes side-effect actions.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task MatchAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, Task> onSuccessAsync,");
        w.WriteLine("Func<Error, Task> onFailureAsync)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (onSuccessAsync is null) throw new ArgumentNullException(nameof(onSuccessAsync));");
        w.WriteLine("if (onFailureAsync is null) throw new ArgumentNullException(nameof(onFailureAsync));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("await onSuccessAsync(s.Result).ConfigureAwait(false);");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("await onFailureAsync(f.Error).ConfigureAwait(false);");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}