// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class RecoverEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Recover.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitRecover(w, op);
        w.WriteLine();
        EmitRecoverAsyncFunc(w, op);
        w.WriteLine();
        EmitRecoverAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Recover<T>(Operation<T>, Func<Error, T>)
    // ---------------------------------------------------------------------
    private static void EmitRecover(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name; // "Result"
        string errorField = op.ErrorField.Name;   // "Error"
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Recovers from a failed operation by mapping the error into a successful value.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"recover\">The function that converts an error into a successful value.</param>");
        w.WriteLine("/// <returns>A recovered success or the original success.</returns>");
        w.WriteLine($"public static Operation<T> Recover<T>(this Operation<T> op, Func<{errorType}, T> recover)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (recover is null) throw new ArgumentNullException(nameof(recover));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => Success(recover(f.{errorField})),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Operation<T>, Func<Error, Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncFunc(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously recovers from a failed operation by mapping the error into a successful value.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"recoverAsync\">The async function that converts an error into a successful value.</param>");
        w.WriteLine("/// <returns>A task producing a recovered success or the original success.</returns>");
        w.WriteLine($"public static async Task<Operation<T>> RecoverAsync<T>(this Operation<T> op, Func<{errorType}, Task<T>> recoverAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (recoverAsync is null) throw new ArgumentNullException(nameof(recoverAsync));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} f => Success(await recoverAsync(f.{errorField}).ConfigureAwait(false)),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Operation<T>, Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously recovers from a failed operation using a precomputed task.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"nextTask\">The task producing the recovered value.</param>");
        w.WriteLine("/// <returns>A task producing a recovered success or the original success.</returns>");
        w.WriteLine("public static async Task<Operation<T>> RecoverAsync<T>(this Operation<T> op, Task<T> nextTask)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (nextTask is null) throw new ArgumentNullException(nameof(nextTask));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{failure} => Success(await nextTask.ConfigureAwait(false)),");
        w.WriteLine($"{success} s => Success(s.{resultField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}