// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class RecoverEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Recover.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitRecoverValue(w, op);
        w.WriteLine();

        EmitRecoverAsyncValue(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Recover<T>(Func<Error, T>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverValue(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Recovers from a failed operation by converting the error into a successful value.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<T> Recover<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<Error, T> recover)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (recover is null) throw new ArgumentNullException(nameof(recover));");
        w.WriteLine();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => s,");
        w.WriteLine($"{failure} f => new Operation<T>.Success(recover(f.Error)),");
        w.WriteLine("_ => throw new InvalidOperationException()");

        w.Unindent();
        w.WriteLine("};");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Func<Error, Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncValue(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously recovers from a failed operation by converting the error into a successful value.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> RecoverAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<Error, Task<T>> recoverAsync)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (recoverAsync is null) throw new ArgumentNullException(nameof(recoverAsync));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("return s;");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return new Operation<T>.Success(await recoverAsync(f.Error).ConfigureAwait(false));");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException();");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}