// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class RecoverEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Recover.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitRecover(w, op);
        w.WriteLine();
        EmitRecoverAsyncFunc(w, op);
        w.WriteLine();
        EmitRecoverAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Recover<T>(Func<ErrorType, T>)
    // ---------------------------------------------------------------------
    private static void EmitRecover(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine($"public static Operation<T> Recover<T>(this Operation<T> op, Func<{errorType}, T> recover)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{failure} f => Success(recover(f.{errorField})),");
        w.WriteLine($"{success} s => s,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Func<ErrorType, Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncFunc(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine($"public static async Task<Operation<T>> RecoverAsync<T>(this Operation<T> op, Func<{errorType}, Task<T>> recover)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{failure} f => Success(await recover(f.{errorField}).ConfigureAwait(false)),");
        w.WriteLine($"{success} s => s,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // RecoverAsync<T>(Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitRecoverAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        string resultField = op.ResultField.Name;

        w.WriteLine("public static async Task<Operation<T>> RecoverAsync<T>(this Operation<T> op, Task<T> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{failure} => Success(await task.ConfigureAwait(false)),");
        w.WriteLine($"{success} s => s,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}