// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class SwitchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Switch.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSwitch(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Switch<T>(Action<T>, Action<ErrorType>)
    // ---------------------------------------------------------------------
    private static void EmitSwitch(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("public static void Switch<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Action<T> onSuccess,");
        w.WriteLine($"Action<{errorType}> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        // Success
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"onSuccess(s.{resultField});");
        w.WriteLine("return;");
        w.Unindent();
        w.WriteLine();

        // Failure
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"onFailure(f.{errorField});");
        w.WriteLine("return;");
        w.Unindent();
        w.WriteLine();

        // Default
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}