// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class SwitchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Switch.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSwitch(w, op);
        w.WriteLine();
        EmitSwitchAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Switch<T>(Action<T>, Action<Error>)
    // ---------------------------------------------------------------------
    private static void EmitSwitch(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Executes one of two actions depending on whether the operation succeeded or failed.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static void Switch<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Action<T> onSuccess,");
        w.WriteLine("Action<Error> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"onSuccess(s.{resultField});");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"onFailure(f.{errorField});");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // SwitchAsync<T>(Func<T, Task>, Func<Error, Task>)
    // ---------------------------------------------------------------------
    private static void EmitSwitchAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes one of two actions depending on whether the operation succeeded or failed.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task SwitchAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, Task> onSuccess,");
        w.WriteLine("Func<Error, Task> onFailure)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"await onSuccess(s.{resultField}).ConfigureAwait(false);");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"await onFailure(f.{errorField}).ConfigureAwait(false);");
        w.WriteLine("break;");
        w.Unindent();

        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("throw new InvalidOperationException(\"Unknown Operation state.\");");
        w.Unindent();

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}