// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class SwitchEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Switch.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitSwitch(w, op);
        w.WriteLine();
        EmitSwitchAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Switch<T, U>(Operation<T>, Func<T, Operation<U>>, Func<Error, Operation<U>>)
    // ---------------------------------------------------------------------
    private static void EmitSwitch(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name; // "Result"
        string errorField = op.ErrorField.Name;   // "Error"
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Branches on the operation, mapping success and failure into new operations.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The input result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"U\">The resulting operation type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"onSuccess\">The function to execute when the operation is a success.</param>");
        w.WriteLine("/// <param name=\"onFailure\">The function to execute when the operation is a failure.</param>");
        w.WriteLine("/// <returns>The resulting operation.</returns>");
        w.WriteLine($"public static Operation<U> Switch<T, U>(this Operation<T> op, Func<T, Operation<U>> onSuccess, Func<{errorType}, Operation<U>> onFailure)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccess is null) throw new ArgumentNullException(nameof(onSuccess));");
        w.WriteLine("if (onFailure is null) throw new ArgumentNullException(nameof(onFailure));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => onSuccess(s.{resultField}),");
        w.WriteLine($"{failure} f => onFailure(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // SwitchAsync<T, U>(Operation<T>, Func<T, Task<Operation<U>>>, Func<Error, Task<Operation<U>>>)
    // ---------------------------------------------------------------------
    private static void EmitSwitchAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously branches on the operation, mapping success and failure into new operations.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The input result type.</typeparam>");
        w.WriteLine("/// <typeparam name=\"U\">The resulting operation type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"onSuccessAsync\">The async function to execute when the operation is a success.</param>");
        w.WriteLine("/// <param name=\"onFailureAsync\">The async function to execute when the operation is a failure.</param>");
        w.WriteLine("/// <returns>A task producing the resulting operation.</returns>");
        w.WriteLine($"public static async Task<Operation<U>> SwitchAsync<T, U>(this Operation<T> op, Func<T, Task<Operation<U>>> onSuccessAsync, Func<{errorType}, Task<Operation<U>>> onFailureAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (onSuccessAsync is null) throw new ArgumentNullException(nameof(onSuccessAsync));");
        w.WriteLine("if (onFailureAsync is null) throw new ArgumentNullException(nameof(onFailureAsync));");
        w.WriteLine();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => await onSuccessAsync(s.{resultField}).ConfigureAwait(false),");
        w.WriteLine($"{failure} f => await onFailureAsync(f.{errorField}).ConfigureAwait(false),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}