// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class TapEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Tap.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitTap(w, op);
        w.WriteLine();
        EmitTapAsync(w, op);
        w.WriteLine();
        EmitTapAsyncTask(w, op);


        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Tap<T>(Operation<T>, Action<T>)
    // ---------------------------------------------------------------------
    private static void EmitTap(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string resultField = op.ResultField.Name; // "Result"

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Executes a side-effect when the operation is a success, without altering the result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"action\">The action to execute when the operation is a success.</param>");
        w.WriteLine("/// <returns>The original operation.</returns>");
        w.WriteLine("public static Operation<T> Tap<T>(this Operation<T> op, Action<T> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (action is null) throw new ArgumentNullException(nameof(action));");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"action(s.{resultField});");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("break;");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapAsync<T>(Operation<T>, Func<T, Task>)
    // ---------------------------------------------------------------------
    private static void EmitTapAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes a side-effect when the operation is a success, without altering the result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"actionAsync\">The async action to execute when the operation is a success.</param>");
        w.WriteLine("/// <returns>A task producing the original operation.</returns>");
        w.WriteLine("public static async Task<Operation<T>> TapAsync<T>(this Operation<T> op, Func<T, Task> actionAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (actionAsync is null) throw new ArgumentNullException(nameof(actionAsync));");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"await actionAsync(s.{resultField}).ConfigureAwait(false);");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("break;");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapAsync<T>(Task<Operation<T>>, Action<T>)
    // ---------------------------------------------------------------------
    private static void EmitTapAsyncTask(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string resultField = op.ResultField.Name;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Observes the successful result of an asynchronous operation without altering it.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> TapAsync<T>(this Task<Operation<T>> opTask, Action<T> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (opTask is null) throw new ArgumentNullException(nameof(opTask));");
        w.WriteLine("if (action is null) throw new ArgumentNullException(nameof(action));");
        w.WriteLine();
        w.WriteLine("var op = await opTask.ConfigureAwait(false);");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine($"action(s.{resultField});");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("break;");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }
}