// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class TapErrorEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.TapError.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitTapError(w, op);
        w.WriteLine();
        EmitTapErrorAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapError<T>(Operation<T>, Action<Error>)
    // ---------------------------------------------------------------------
    private static void EmitTapError(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name; // "Error"
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Executes a side-effect when the operation is a failure, without altering the result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"action\">The action to execute when the operation is a failure.</param>");
        w.WriteLine("/// <returns>The original operation.</returns>");
        w.WriteLine($"public static Operation<T> TapError<T>(this Operation<T> op, Action<{errorType}> action)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (action is null) throw new ArgumentNullException(nameof(action));");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"action(f.{errorField});");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("break;");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TapErrorAsync<T>(Operation<T>, Func<Error, Task>)
    // ---------------------------------------------------------------------
    private static void EmitTapErrorAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes a side-effect when the operation is a failure, without altering the result.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The operation result type.</typeparam>");
        w.WriteLine("/// <param name=\"op\">The source operation.</param>");
        w.WriteLine("/// <param name=\"actionAsync\">The async action to execute when the operation is a failure.</param>");
        w.WriteLine("/// <returns>A task producing the original operation.</returns>");
        w.WriteLine($"public static async Task<Operation<T>> TapErrorAsync<T>(this Operation<T> op, Func<{errorType}, Task> actionAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (actionAsync is null) throw new ArgumentNullException(nameof(actionAsync));");
        w.WriteLine();
        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine($"await actionAsync(f.{errorField}).ConfigureAwait(false);");
        w.WriteLine("break;");
        w.Unindent();
        w.WriteLine("default:");
        w.Indent();
        w.WriteLine("break;");
        w.Unindent();
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");
    }
}