// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class ToStringEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.ToString.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        // Header
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine();

        // Namespace
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();

        // Partial union root
        w.WriteLine($"public abstract partial record {op.Union.Name}<T>");
        w.WriteLine("{");
        w.Indent();

        EmitToString(w, op);

        w.Unindent();
        w.WriteLine("}");

        return w.ToString();
    }

    private static void EmitToString(CodeWriter w, OperationModel op)
    {
        string successFqn = op.SuccessCaseFQN;   // global::OpFlow.Operation<T>.Success
        string failureFqn = op.FailureCaseFQN;   // global::OpFlow.Operation<T>.Failure

        string resultField = op.ResultField.Name; // "Result"
        string errorField = op.ErrorField.Name;   // "Error"

        w.WriteLine("public override string ToString()");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("return this switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{successFqn} s => $\"Success: {{s.{resultField}}}\",");
        w.WriteLine($"{failureFqn} f => $\"Failure: {{f.{errorField}}}\",");

        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");

        w.Unindent();
        w.WriteLine("}");
    }
}