// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class TryEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Try.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitTry(w, op);
        w.WriteLine();
        EmitTryAsyncFunc(w, op);
        w.WriteLine();
        EmitTryAsyncTask(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Try<T>(Func<T>)
    // ---------------------------------------------------------------------
    private static void EmitTry(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Executes a function and wraps its result in an operation, capturing exceptions as failures.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"func\">The function to execute.</param>");
        w.WriteLine("/// <returns>A successful operation or a failure if an exception occurs.</returns>");
        w.WriteLine("public static Operation<T> Try<T>(Func<T> func)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (func is null) throw new ArgumentNullException(nameof(func));");
        w.WriteLine();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(func());");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TryAsync<T>(Func<Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitTryAsyncFunc(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously executes a function and wraps its result in an operation, capturing exceptions as failures.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"funcAsync\">The async function to execute.</param>");
        w.WriteLine("/// <returns>A task producing a successful operation or a failure if an exception occurs.</returns>");
        w.WriteLine("public static async Task<Operation<T>> TryAsync<T>(Func<Task<T>> funcAsync)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (funcAsync is null) throw new ArgumentNullException(nameof(funcAsync));");
        w.WriteLine();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("T value = await funcAsync().ConfigureAwait(false);");
        w.WriteLine("return Success(value);");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TryAsync<T>(Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitTryAsyncTask(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Wraps a task result in an operation, capturing exceptions as failures.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <typeparam name=\"T\">The result type.</typeparam>");
        w.WriteLine("/// <param name=\"task\">The task to await.</param>");
        w.WriteLine("/// <returns>A task producing a successful operation or a failure if an exception occurs.</returns>");
        w.WriteLine("public static async Task<Operation<T>> TryAsync<T>(Task<T> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (task is null) throw new ArgumentNullException(nameof(task));");
        w.WriteLine();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("T value = await task.ConfigureAwait(false);");
        w.WriteLine("return Success(value);");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return FailureOf<T>(Error.FromException(ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }
}