// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class TryEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Try.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitTryFunc(w, op);
        w.WriteLine();
        EmitTryFuncAsync(w, op);
        w.WriteLine();
        EmitTryTaskAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Try<T>(Func<T>)
    // ---------------------------------------------------------------------
    private static void EmitTryFunc(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;
        string unexpectedType = $"{errorType}.Unexpected";

        w.WriteLine("public static Operation<T> Try<T>(Func<T> func)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(func());");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(new {unexpectedType}(ex.Message, ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TryAsync<T>(Func<Task<T>>)
    // ---------------------------------------------------------------------
    private static void EmitTryFuncAsync(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;
        string unexpectedType = $"{errorType}.Unexpected";

        w.WriteLine("public static async Task<Operation<T>> TryAsync<T>(Func<Task<T>> func)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(await func().ConfigureAwait(false));");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(new {unexpectedType}(ex.Message, ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // TryAsync<T>(Task<T>)
    // ---------------------------------------------------------------------
    private static void EmitTryTaskAsync(CodeWriter w, OperationModel op)
    {
        string errorType = op.ErrorField.Type;
        string unexpectedType = $"{errorType}.Unexpected";

        w.WriteLine("public static async Task<Operation<T>> TryAsync<T>(Task<T> task)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return Success(await task.ConfigureAwait(false));");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine("catch (Exception ex)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(new {unexpectedType}(ex.Message, ex));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
    }
}