// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class ValidateEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Validate.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitValidateMessage(w, op);
        w.WriteLine();

        EmitValidateFactory(w, op);
        w.WriteLine();

        EmitValidateAsyncMessage(w, op);
        w.WriteLine();

        EmitValidateAsyncFactory(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Validate<T>(predicate, message, fields)
    // ---------------------------------------------------------------------
    private static void EmitValidateMessage(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("public static Operation<T> Validate<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, bool> predicate,");
        w.WriteLine("string message,");
        w.WriteLine("params string[] fields)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (predicate is null) throw new ArgumentNullException(nameof(predicate));");
        w.WriteLine("if (message is null) throw new ArgumentNullException(nameof(message));");
        w.WriteLine("if (fields is null) throw new ArgumentNullException(nameof(fields));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("if (predicate(s.Result)) return s;");
        w.WriteLine("return new Operation<T>.Failure(new Error.Validation(message, fields));");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return f;");
        w.Unindent();

        w.WriteLine("default: throw new InvalidOperationException();");

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Validate<T>(predicate, errorFactory)
    // ---------------------------------------------------------------------
    private static void EmitValidateFactory(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("public static Operation<T> Validate<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, bool> predicate,");
        w.WriteLine("Func<T, Error> errorFactory)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (predicate is null) throw new ArgumentNullException(nameof(predicate));");
        w.WriteLine("if (errorFactory is null) throw new ArgumentNullException(nameof(errorFactory));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("if (predicate(s.Result)) return s;");
        w.WriteLine("return new Operation<T>.Failure(errorFactory(s.Result));");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return f;");
        w.Unindent();

        w.WriteLine("default: throw new InvalidOperationException();");

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // ValidateAsync<T>(predicateAsync, message, fields)
    // ---------------------------------------------------------------------
    private static void EmitValidateAsyncMessage(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("public static async Task<Operation<T>> ValidateAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, Task<bool>> predicateAsync,");
        w.WriteLine("string message,");
        w.WriteLine("params string[] fields)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (predicateAsync is null) throw new ArgumentNullException(nameof(predicateAsync));");
        w.WriteLine("if (message is null) throw new ArgumentNullException(nameof(message));");
        w.WriteLine("if (fields is null) throw new ArgumentNullException(nameof(fields));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("if (await predicateAsync(s.Result).ConfigureAwait(false)) return s;");
        w.WriteLine("return new Operation<T>.Failure(new Error.Validation(message, fields));");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return f;");
        w.Unindent();

        w.WriteLine("default: throw new InvalidOperationException();");

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // ValidateAsync<T>(predicateAsync, errorFactory)
    // ---------------------------------------------------------------------
    private static void EmitValidateAsyncFactory(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;

        w.WriteLine("public static async Task<Operation<T>> ValidateAsync<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine("Func<T, Task<bool>> predicateAsync,");
        w.WriteLine("Func<T, Error> errorFactory)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (predicateAsync is null) throw new ArgumentNullException(nameof(predicateAsync));");
        w.WriteLine("if (errorFactory is null) throw new ArgumentNullException(nameof(errorFactory));");
        w.WriteLine();

        w.WriteLine("switch (op)");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"case {success} s:");
        w.Indent();
        w.WriteLine("if (await predicateAsync(s.Result).ConfigureAwait(false)) return s;");
        w.WriteLine("return new Operation<T>.Failure(errorFactory(s.Result));");
        w.Unindent();

        w.WriteLine($"case {failure} f:");
        w.Indent();
        w.WriteLine("return f;");
        w.Unindent();

        w.WriteLine("default: throw new InvalidOperationException();");

        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}