// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class ValidateEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.Validate.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitValidateMessage(w, op);
        w.WriteLine();
        EmitValidateError(w, op);
        w.WriteLine();
        EmitValidateAsyncMessage(w, op);
        w.WriteLine();
        EmitValidateAsyncError(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Validate<T>(Func<T, bool>, string)
    // ---------------------------------------------------------------------
    private static void EmitValidateMessage(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorType = op.ErrorField.Type;
        string validationType = $"{errorType}.Validation";

        w.WriteLine("public static Operation<T> Validate<T>(this Operation<T> op, Func<T, bool> predicate, string message)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => predicate(s.{resultField}) ? op : FailureOf<T>(new {validationType}(message)),");
        w.WriteLine($"{failure} f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // Validate<T>(Func<T, bool>, ErrorType)
    // ---------------------------------------------------------------------
    private static void EmitValidateError(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine($"public static Operation<T> Validate<T>(this Operation<T> op, Func<T, bool> predicate, {errorType} error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => predicate(s.{resultField}) ? op : FailureOf<T>(error),");
        w.WriteLine($"{failure} f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // ValidateAsync<T>(Func<T, Task<bool>>, string)
    // ---------------------------------------------------------------------
    private static void EmitValidateAsyncMessage(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorType = op.ErrorField.Type;
        string validationType = $"{errorType}.Validation";

        w.WriteLine("public static async Task<Operation<T>> ValidateAsync<T>(this Operation<T> op, Func<T, Task<bool>> predicate, string message)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => await predicate(s.{resultField}).ConfigureAwait(false) ? op : FailureOf<T>(new {validationType}(message)),");
        w.WriteLine($"{failure} f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // ValidateAsync<T>(Func<T, Task<bool>>, ErrorType)
    // ---------------------------------------------------------------------
    private static void EmitValidateAsyncError(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine($"public static async Task<Operation<T>> ValidateAsync<T>(this Operation<T> op, Func<T, Task<bool>> predicate, {errorType} error)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();

        w.WriteLine($"{success} s => await predicate(s.{resultField}).ConfigureAwait(false) ? op : FailureOf<T>(error),");
        w.WriteLine($"{failure} f => f,");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");

        w.Unindent();
        w.WriteLine("};");
        w.Unindent();
        w.WriteLine("}");
    }
}