// Copyright (c) 2026 Paulo Pocinho.

using OpFlow.Generators.Semantics;

namespace OpFlow.Generators.Emission.Emitters;

internal sealed class ValidateAllEmitter : IOperationEmitter
{
    public string FileName(OperationModel op) => $"{op.Union.Name}.ValidateAll.g.cs";

    public string Emit(OperationModel op)
    {
        CodeWriter w = new CodeWriter();

        EmitHeader(w);
        EmitNamespace(w, op);

        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using System;");
        w.WriteLine("using System.Collections.Generic;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine();
    }

    private static void EmitNamespace(CodeWriter w, OperationModel op)
    {
        w.WriteLine($"namespace {op.Namespace};");
        w.WriteLine();
        EmitClass(w, op);
    }

    private static void EmitClass(CodeWriter w, OperationModel op)
    {
        w.WriteLine("public static partial class Operation");
        w.WriteLine("{");
        w.Indent();

        EmitValidateAll(w, op);
        w.WriteLine();
        EmitValidateAllAsync(w, op);

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // ValidateAll<T>(Operation<T>, IEnumerable<(Func<T,bool>, Func<T,Error>)>)
    // ---------------------------------------------------------------------
    private static void EmitValidateAll(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Applies multiple validation rules to a successful operation, returning the first validation error encountered.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static Operation<T> ValidateAll<T>(");
        w.Indent();
        w.WriteLine("this Operation<T> op,");
        w.WriteLine($"IEnumerable<(Func<T, bool> predicate, Func<T, {errorType}> errorFactory)> rules)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (rules is null) throw new ArgumentNullException(nameof(rules));");
        w.WriteLine();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => Validate(s),");
        w.WriteLine($"{failure} f => FailureOf<T>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.WriteLine();

        // Local function for multi-statement success arm
        w.WriteLine($"Operation<T> Validate({success} s)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("foreach (var (predicate, errorFactory) in rules)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (predicate is null) throw new ArgumentNullException(nameof(predicate));");
        w.WriteLine("if (errorFactory is null) throw new ArgumentNullException(nameof(errorFactory));");
        w.WriteLine();
        w.WriteLine($"if (!predicate(s.{resultField}))");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(errorFactory(s.{resultField}));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }

    // ---------------------------------------------------------------------
    // ValidateAllAsync<T>(Task<Operation<T>>, IEnumerable<(Func<T,Task<bool>>, Func<T,Error>)>)
    // ---------------------------------------------------------------------
    private static void EmitValidateAllAsync(CodeWriter w, OperationModel op)
    {
        string success = op.SuccessCaseFQN;
        string failure = op.FailureCaseFQN;
        string resultField = op.ResultField.Name;
        string errorField = op.ErrorField.Name;
        string errorType = op.ErrorField.Type;

        w.WriteLine("/// <summary>");
        w.WriteLine("/// Asynchronously applies multiple validation rules to a successful operation, returning the first validation error encountered.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public static async Task<Operation<T>> ValidateAllAsync<T>(");
        w.Indent();
        w.WriteLine("this Task<Operation<T>> opTask,");
        w.WriteLine($"IEnumerable<(Func<T, Task<bool>> predicateAsync, Func<T, {errorType}> errorFactory)> rules)");
        w.Unindent();
        w.WriteLine("{");
        w.Indent();

        w.WriteLine("if (rules is null) throw new ArgumentNullException(nameof(rules));");
        w.WriteLine();
        w.WriteLine("Operation<T> op = await opTask.ConfigureAwait(false);");
        w.WriteLine();

        w.WriteLine("return op switch");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"{success} s => await ValidateAsync(s).ConfigureAwait(false),");
        w.WriteLine($"{failure} f => FailureOf<T>(f.{errorField}),");
        w.WriteLine("_ => throw new InvalidOperationException(\"Unknown Operation state.\")");
        w.Unindent();
        w.WriteLine("};");
        w.WriteLine();

        // Local async validator
        w.WriteLine($"async Task<Operation<T>> ValidateAsync({success} s)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("foreach (var (predicateAsync, errorFactory) in rules)");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine("if (predicateAsync is null) throw new ArgumentNullException(nameof(predicateAsync));");
        w.WriteLine("if (errorFactory is null) throw new ArgumentNullException(nameof(errorFactory));");
        w.WriteLine();
        w.WriteLine($"if (!await predicateAsync(s.{resultField}).ConfigureAwait(false))");
        w.WriteLine("{");
        w.Indent();
        w.WriteLine($"return FailureOf<T>(errorFactory(s.{resultField}));");
        w.Unindent();
        w.WriteLine("}");
        w.Unindent();
        w.WriteLine("}");
        w.WriteLine();
        w.WriteLine("return op;");
        w.Unindent();
        w.WriteLine("}");

        w.Unindent();
        w.WriteLine("}");
    }
}